'use strict';

/**
 * Page definitions — the full queue of pages to generate.
 * Each entry describes one output HTML file.
 */

// ── Destination pages (country level) ────────────────────────────────────────

const DESTINATION_PAGES = [
  {
    id: 'marokko',
    file: 'marokko.html',
    type: 'destination',
    icon: '🇲🇦',
    nameDe: 'Marokko',
    title: 'Urlaub in Marokko – Marrakesch, Agadir & mehr | JetztBuchbar.de',
    description: 'Marokko Urlaub 2026 günstig buchen: Marrakesch, Agadir, Essaouira. Beste Reisezeit, Tipps und Angebote für DACH-Reisende.',
    h1Parts: ['Urlaub in', 'Marokko'],
    heroSub: 'Orientalisches Flair, endlose Wüsten und traumhafte Atlantikstrände – Marokko ist ein Reiseziel der Gegensätze.',
    wikiSearch: 'Marokko',
    climateKey: 'marokko',
    countryKey: 'marokko',
    tips: [
      'Für DACH-Bürger ist kein Visum erforderlich – bei einer Aufenthaltsdauer bis zu 90 Tagen reicht der Reisepass.',
      'Die beste Reisezeit für Strand und Sightseeing ist März bis Mai sowie September bis November.',
      'Feilschen ist auf den Souks Tradition – aber respektvoll und mit Humor. Startpreis oft 2–3x höher als Endpreis.',
      'Frauen sollten außerhalb der Resorts die Schultern und Knie bedecken, besonders in konservativeren Städten.',
      'Trinkwasser nur aus verschlossenen Flaschen trinken – Leitungswasser ist nicht für Touristen geeignet.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Marokko?', a: 'Nein. Bürger aus Deutschland, Österreich und der Schweiz können bis zu 90 Tage visumfrei einreisen. Ein gültiger Reisepass ist erforderlich.' },
      { q: 'Wie lange ist der Flug nach Marokko?', a: 'Von Wien oder München dauert ein Direktflug nach Marrakesch oder Agadir ca. 3,5–4 Stunden.' },
      { q: 'Welche Währung gilt in Marokko?', a: 'Die offizielle Währung ist der Marokkanische Dirham (MAD). Dieser kann nicht im Ausland gekauft werden – Geldwechsel am Flughafen oder an Wechselstuben vor Ort.' },
      { q: 'Ist Marokko sicher für Touristen?', a: 'Die Haupttouristenzentren wie Marrakesch, Agadir und Fes gelten als sicher. Wie überall empfiehlt sich Aufmerksamkeit in belebten Souks wegen Taschendiebstahls.' },
      { q: 'Was sollte ich in Marokko unbedingt gesehen haben?', a: 'Djemaa el-Fna in Marrakesch, die Sahara bei Merzouga, die blaue Stadt Chefchaouen, Essaouira am Atlantik und die Königsstadt Fes.' },
    ],
    poiSearch: 'Marrakesch',
  },
  {
    id: 'tunesien',
    file: 'tunesien.html',
    type: 'destination',
    icon: '🇹🇳',
    nameDe: 'Tunesien',
    title: 'Urlaub in Tunesien – Djerba, Hammamet & mehr | JetztBuchbar.de',
    description: 'Tunesien Urlaub 2026 günstig buchen: Djerba, Hammamet, Sousse. Beste Reisezeit, Tipps und All-Inclusive-Angebote.',
    h1Parts: ['Urlaub in', 'Tunesien'],
    heroSub: 'Weißblaue Häuser, phönizische Geschichte und goldene Sandstrände am Mittelmeer – Tunesien bietet Urlaub für jeden Geldbeutel.',
    wikiSearch: 'Tunesien',
    climateKey: 'tunesien',
    countryKey: 'tunesien',
    tips: [
      'Kein Visum erforderlich für DACH-Bürger bei Aufenthalten bis zu 90 Tagen.',
      'All-Inclusive-Resorts in Djerba, Hammamet und Sousse bieten hervorragendes Preis-Leistungs-Verhältnis.',
      'Die beste Reisezeit ist April bis Juni sowie September bis Oktober – angenehme 25–30 °C ohne Hochsommerhitze.',
      'Trinkwasser nur aus Flaschen – Leitungswasser sollte nicht getrunken werden.',
      'Abends einen Hauch der Medina erleben: Tunis-Medina ist UNESCO-Welterbe und einen Tagesausflug wert.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Tunesien?', a: 'Nein. Bürger aus Deutschland, Österreich und der Schweiz reisen bis zu 90 Tage visumfrei ein.' },
      { q: 'Wie lange dauert der Flug nach Tunesien?', a: 'Von Wien oder München beträgt die Flugzeit nach Djerba oder Tunis ca. 2,5–3 Stunden Direktflug.' },
      { q: 'Ist Tunesien sicher für Touristen?', a: 'Die Touristenzentren wie Djerba, Hammamet und Sousse sind gut gesichert. Aktuelle Reisewarnungen des Außenministeriums sollten vor der Reise geprüft werden.' },
      { q: 'Welche Währung gilt in Tunesien?', a: 'Der Tunesische Dinar (TND) ist die Landeswährung. Geldwechsel am Flughafen oder in Banken empfohlen – der Dinar darf nicht ausgeführt werden.' },
      { q: 'Was sind die beliebtesten Reiseziele in Tunesien?', a: 'Djerba für Badeurlaub, Hammamet für Familien, Sousse für Aktivurlauber, und Tunis mit der UNESCO-Medina für Kulturinteressierte.' },
    ],
    poiSearch: 'Djerba',
  },
  {
    id: 'dubai',
    file: 'dubai.html',
    type: 'destination',
    icon: '🇦🇪',
    nameDe: 'Dubai',
    title: 'Urlaub in Dubai – Luxus, Strand & Wüste | JetztBuchbar.de',
    description: 'Dubai Urlaub 2026 günstig buchen: Burj Khalifa, JBR Beach, Wüstensafari. Beste Reisezeit, Tipps und Angebote für DACH-Reisende.',
    h1Parts: ['Urlaub in', 'Dubai'],
    heroSub: 'Wolkenkratzer-Skyline, goldene Strände und abenteuerliche Wüstensafaris – Dubai ist das Reiseziel für unvergessliche Erlebnisse.',
    wikiSearch: 'Dubai',
    climateKey: 'dubai',
    countryKey: 'dubai',
    tips: [
      'Kein Visum erforderlich für DACH-Bürger – bei der Einreise gibt es automatisch ein 30-Tage-Visum.',
      'Beste Reisezeit: Oktober bis April mit angenehmen 22–30 °C. Sommer (Juni–August) ist mit bis zu 45 °C extrem heiß.',
      'Kleidungsregeln beachten: In Einkaufszentren, öffentlichen Verkehrsmitteln und Moscheen sind bedeckte Schultern und Knie Pflicht.',
      'Alkohol ist nur in lizenzierten Hotels und Restaurants erhältlich – in der Öffentlichkeit streng verboten.',
      'Die Metro ist das schnellste und günstigste Verkehrsmittel – Nol Card kaufen und Staus vermeiden.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Dubai?', a: 'Nein. DACH-Bürger erhalten bei der Einreise automatisch ein kostenloses 30-Tage-Visum. Eine Verlängerung ist möglich.' },
      { q: 'Wie lange ist der Flug nach Dubai?', a: 'Von Wien oder München dauert ein Direktflug nach Dubai ca. 5,5–6 Stunden. Emirates und Lufthansa bieten tägliche Verbindungen.' },
      { q: 'Welche Währung gilt in Dubai?', a: 'Der Dirham der Vereinigten Arabischen Emirate (AED). 1 Euro entspricht ca. 3,9 AED. Kreditkarten sind überall akzeptiert.' },
      { q: 'Ist Dubai für Familien geeignet?', a: 'Ja, Dubai ist sehr familienfreundlich. Wild Wadi Waterpark, Dubai Frame, Dubai Zoo und unzählige Malls bieten Unterhaltung für alle Altersgruppen.' },
      { q: 'Was kostet ein Urlaub in Dubai?', a: 'Dubai ist teuer, aber es gibt Budgetoptionen. Ein Mittelklasse-Hotel kostet ab 80–120 € pro Nacht. Restaurants variieren stark – von günstigen Food Courts bis zu Luxusrestaurants.' },
    ],
    poiSearch: 'Dubai',
  },
  {
    id: 'kroatien',
    file: 'kroatien.html',
    type: 'destination',
    icon: '🇭🇷',
    nameDe: 'Kroatien',
    title: 'Urlaub in Kroatien – Dubrovnik, Split & Inseln | JetztBuchbar.de',
    description: 'Kroatien Urlaub 2026 günstig buchen: Dubrovnik, Split, Hvar, Nationalparks. Beste Reisezeit, Tipps und Angebote.',
    h1Parts: ['Urlaub in', 'Kroatien'],
    heroSub: 'Kristallklares Adriawasser, mittelalterliche Altstädte und unberührte Nationalparks – Kroatien ist Europas Geheimtipp.',
    wikiSearch: 'Kroatien',
    climateKey: 'kroatien',
    countryKey: 'kroatien',
    tips: [
      'Als EU-Bürger (Deutschland, Österreich) reisen Sie visumfrei ein. Schweizer benötigen nur den Reisepass.',
      'Kroatien verwendet seit 2023 den Euro (€) – kein Geldwechsel mehr nötig.',
      'Beste Reisezeit für Badeurlaub: Juni bis September. Mai und Oktober ideal für Städtereisen ohne Massen.',
      'Frühzeitig buchen: Dubrovnik und Hvar sind im Sommer extrem beliebt – Ferienunterkünfte früh reservieren.',
      'Mit der Fähre lassen sich die kroatischen Inseln (Hvar, Brač, Korčula) einfach und günstig erreichen.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Kroatien?', a: 'Nein. Kroatien ist seit 2023 EU-Mitglied und Teil des Schengenraums. EU-Bürger reisen mit Personalausweis visumfrei ein.' },
      { q: 'Wie lange dauert der Flug nach Kroatien?', a: 'Von Wien nach Dubrovnik oder Split dauert ein Direktflug ca. 1–1,5 Stunden. In der Saison gibt es günstige Direktverbindungen.' },
      { q: 'Welche Währung gilt in Kroatien?', a: 'Kroatien hat seit Januar 2023 den Euro (€) eingeführt. Kein Geldwechsel notwendig für DACH-Reisende.' },
      { q: 'Was kostet Urlaub in Kroatien?', a: 'Kroatien ist günstiger als Westeuropa, aber teurer als Türkei oder Ägypten. Apartments und Ferienhäuser sind besonders beliebt und preiswert.' },
      { q: 'Welche Nationalparks lohnen sich in Kroatien?', a: 'Die Plitvicer Seen (UNESCO-Welterbe), der Nationalpark Krka mit Wasserfällen und der Kornati-Archipel sind absolute Highlights.' },
    ],
    poiSearch: 'Dubrovnik',
  },
  {
    id: 'portugal',
    file: 'portugal.html',
    type: 'destination',
    icon: '🇵🇹',
    nameDe: 'Portugal',
    title: 'Urlaub in Portugal – Lissabon, Algarve & mehr | JetztBuchbar.de',
    description: 'Portugal Urlaub 2026 günstig buchen: Lissabon, Algarve, Porto. Beste Reisezeit, Tipps und Angebote für DACH-Reisende.',
    h1Parts: ['Urlaub in', 'Portugal'],
    heroSub: 'Goldene Steilküsten, Fado-Musik, Pastéis de Nata und das mildeste Klima Westeuropas – Portugal begeistert alle Sinne.',
    wikiSearch: 'Portugal',
    climateKey: 'portugal',
    countryKey: 'portugal',
    tips: [
      'Als EU-Bürger reisen Sie visumfrei nach Portugal. Ein gültiger Personalausweis genügt.',
      'Die Algarve-Küste im Süden hat die schönsten Strände – beste Zeit April bis Oktober.',
      'Lissabon ist ganzjährig eine Reise wert – mild, kulturreich und günstiger als andere Hauptstädte.',
      'Pastéis de Belém in Lissabon probieren – die Original-Pastel de Nata Bäckerei aus dem Jahr 1837.',
      'Mietwagen empfohlen: Portugals schönste Ecken (Alentejo, Douro-Tal) sind mit dem Auto am besten erreichbar.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Portugal?', a: 'Nein. Portugal ist EU-Mitglied. DACH-Bürger reisen mit Personalausweis visumfrei ein.' },
      { q: 'Wann ist die beste Reisezeit für Portugal?', a: 'Mai bis Oktober ist ideal für Badeurlaub. Lissabon und Porto lohnen sich das ganze Jahr – mild, auch im Winter.' },
      { q: 'Wie lange ist der Flug nach Portugal?', a: 'Von Wien oder München dauert ein Direktflug nach Lissabon oder Faro ca. 3–3,5 Stunden.' },
      { q: 'Was ist die beliebteste Region in Portugal?', a: 'Die Algarve im Süden für Strand und Sonne, Lissabon für Stadtkultur, und der Norden (Porto, Douro-Tal) für Wein und Natur.' },
      { q: 'Welche Währung gilt in Portugal?', a: 'Euro (€) – kein Geldwechsel nötig.' },
    ],
    poiSearch: 'Lissabon',
  },
  {
    id: 'bulgarien',
    file: 'bulgarien.html',
    type: 'destination',
    icon: '🇧🇬',
    nameDe: 'Bulgarien',
    title: 'Urlaub in Bulgarien – Sonnenstrand, Goldstrand & Sofia | JetztBuchbar.de',
    description: 'Bulgarien Urlaub 2026 günstig buchen: Sonnenstrand, Goldstrand, Sofia, Varna. Günstigste Schwarzmeerküste Europas.',
    h1Parts: ['Urlaub in', 'Bulgarien'],
    heroSub: 'Europas günstigstes Badeziel: Sonnenstrand, Goldstrand und eine faszinierende Hauptstadt – Bulgarien bietet Qualität zum kleinen Preis.',
    wikiSearch: 'Bulgarien',
    climateKey: 'bulgarien',
    countryKey: 'bulgarien',
    tips: [
      'Als EU-Bürger reisen Sie visumfrei ein – Personalausweis genügt.',
      'Bulgarien ist eines der günstigsten EU-Reiseziele: Hotel, Essen und Aktivitäten kosten deutlich weniger als in Westeuropa.',
      'Die Schwarzmeerküste (Sonnenstrand, Goldstrand) ist ideal für Familien und Budgeturlauber.',
      'Sofia lohnt sich als Städtereise: Alexander-Newski-Kathedrale, Boyana-Kirche (UNESCO) und lebendige Café-Szene.',
      'Bulgarien verwendet noch den Lev (BGN) – Wechselkurs ca. 2 BGN = 1 €.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Bulgarien?', a: 'Nein. Bulgarien ist EU-Mitglied. DACH-Bürger reisen mit Personalausweis visumfrei ein.' },
      { q: 'Ist Bulgarien günstig für Urlaub?', a: 'Ja, Bulgarien gehört zu den günstigsten EU-Reisezielen. All-Inclusive am Sonnenstrand kostet oft ein Drittel von vergleichbaren Angeboten in Spanien.' },
      { q: 'Wie lange dauert der Flug nach Bulgarien?', a: 'Von Wien nach Sofia oder Varna dauert ein Direktflug ca. 1,5–2 Stunden.' },
      { q: 'Welche Währung gilt in Bulgarien?', a: 'Der Bulgarische Lev (BGN) – noch nicht der Euro. Wechselkurs ca. 1,96 BGN pro Euro.' },
      { q: 'Was lohnt sich in Bulgarien neben dem Strand?', a: 'Das Rila-Kloster (UNESCO-Welterbe), das Bachkovo-Kloster, Plovdiv mit der Altstadt und der Nationalpark Pirin sind absolute Empfehlungen.' },
    ],
    poiSearch: 'Sonnenstrand',
  },
  {
    id: 'malta',
    file: 'malta.html',
    type: 'destination',
    icon: '🇲🇹',
    nameDe: 'Malta',
    title: 'Urlaub in Malta – Valletta, Gozo & Strand | JetztBuchbar.de',
    description: 'Malta Urlaub 2026 günstig buchen: Valletta, Gozo, Comino Blue Lagoon. Geschichte, Sonne und kristallklares Mittelmeer.',
    h1Parts: ['Urlaub in', 'Malta'],
    heroSub: 'Der kleinste EU-Staat mit gigantischer Geschichte: Tempelanlagen, Ritterburgen und die berühmte Blue Lagoon erwarten Sie.',
    wikiSearch: 'Malta',
    climateKey: 'malta',
    countryKey: 'malta',
    tips: [
      'Kein Visum nötig als EU-Bürger. Malta ist EU-Mitglied und Schengenland.',
      'Beste Reisezeit: Mai bis Oktober mit 25–35 °C und wenig Regen.',
      'Die Blue Lagoon auf Comino per Fähre besuchen – früh morgens fahren, um Menschenmassen zu vermeiden.',
      'Valletta ist Europas kleinste Hauptstadt und UNESCO-Welterbe – unbedingt die Johanneskathedrale besichtigen.',
      'Englisch ist Amtssprache neben Maltesisch – Verständigung überall problemlos möglich.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Malta?', a: 'Nein. Malta ist EU-Mitglied und Schengenstaat. DACH-Bürger reisen visumfrei ein.' },
      { q: 'Wie lange dauert der Flug nach Malta?', a: 'Von Wien oder München dauert ein Direktflug nach Malta ca. 2,5–3 Stunden.' },
      { q: 'Was ist die Blue Lagoon?', a: 'Die Blue Lagoon auf der kleinen Insel Comino ist eines der schönsten Gewässer Europas – kristallklares, türkisblaues Wasser, ideal zum Schnorcheln und Schwimmen.' },
      { q: 'Welche Währung gilt in Malta?', a: 'Euro (€) – kein Geldwechsel notwendig.' },
      { q: 'Lohnt sich Malta auch für Taucher?', a: 'Ja, Malta ist eines der Top-Tauchreiseziele Europas. Unterwasserhöhlen, Wracks und kristallklares Wasser machen Malta für Taucher sehr attraktiv.' },
    ],
    poiSearch: 'Valletta',
  },
  {
    id: 'zypern',
    file: 'zypern.html',
    type: 'destination',
    icon: '🇨🇾',
    nameDe: 'Zypern',
    title: 'Urlaub in Zypern – Paphos, Ayia Napa & Limassol | JetztBuchbar.de',
    description: 'Zypern Urlaub 2026 günstig buchen: Paphos, Ayia Napa, Limassol, Protaras. Sonne, Strand und antike Geschichte.',
    h1Parts: ['Urlaub in', 'Zypern'],
    heroSub: 'Die Insel der Aphrodite: 340 Sonnentage, antike Stätten und lebhafte Küstenorte machen Zypern zu einem ganzjährigen Reiseziel.',
    wikiSearch: 'Zypern',
    climateKey: 'zypern',
    countryKey: 'zypern',
    tips: [
      'Als EU-Bürger reisen Sie visumfrei nach Zypern ein.',
      'Zypern hat 340 Sonnentage im Jahr – auch Oktober bis April ist sehr angenehm.',
      'Rechtsverkehr gilt in Zypern – das ist ungewöhnlich für ein EU-Land (britisches Erbe).',
      'Paphos ist UNESCO-Welterbe: antike Mosaiken, Aphrodite-Felsen und mittelalterliche Burg gehören zum Pflichtprogramm.',
      'Ayia Napa im Osten für Partytourismus und schöne Strände, Limassol für gehobene Gastronomie und Hafen.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Zypern?', a: 'Nein. Zypern ist EU-Mitglied. DACH-Bürger reisen visumfrei ein.' },
      { q: 'Wann ist die beste Reisezeit für Zypern?', a: 'April bis Oktober für Badeurlaub. Zypern ist auch im Winter mild (15–20 °C) – ideal für Wandern und Kulturreisen.' },
      { q: 'Wie lange dauert der Flug nach Zypern?', a: 'Von Wien oder München beträgt die Flugzeit nach Larnaca ca. 3,5–4 Stunden.' },
      { q: 'Welche Währung gilt in Zypern?', a: 'Euro (€) – kein Geldwechsel notwendig.' },
      { q: 'Was ist der Unterschied zwischen Nord- und Südzypern?', a: 'Der Süden (Republik Zypern) ist EU-Mitglied. Der Norden wird von der Türkei kontrolliert und ist nur eingeschränkt bereisbar. Touristen reisen meist in den Süden.' },
    ],
    poiSearch: 'Paphos',
  },
  {
    id: 'kap-verde',
    file: 'kap-verde.html',
    type: 'destination',
    icon: '🇨🇻',
    nameDe: 'Kap Verde',
    title: 'Urlaub in Kap Verde – Sal, Boa Vista & Santiago | JetztBuchbar.de',
    description: 'Kap Verde Urlaub 2026 buchen: Insel Sal, Boa Vista, Santiago. Ganzjährig Sonne, Surfen und Karibik-Feeling vor Afrika.',
    h1Parts: ['Urlaub in', 'Kap Verde'],
    heroSub: 'Ganzjährig 25 °C, türkisblaues Atlantikmeer und Karibik-Feeling nur 6 Stunden von Europa entfernt – das ist Kap Verde.',
    wikiSearch: 'Kap Verde',
    climateKey: 'kap verde',
    countryKey: 'kap verde',
    tips: [
      'Für DACH-Bürger kein Visum erforderlich – bei der Einreise wird ein Ankunftsvisum ausgestellt (kostenfrei oder geringe Gebühr).',
      'Kap Verde ist ganzjährig bereisbar mit konstant 24–28 °C – kein Sommer-/Winterunterschied.',
      'Sal und Boa Vista sind die Inselkandidaten für Strandurlauber; Santiago für Kultur und Stadtleben.',
      'Der Passat macht Kap Verde zu einem Surfer-Paradies – Windsurf und Kitesurf weltweit bekannt.',
      'Beachte: Infrastruktur auf kleineren Inseln ist einfacher – Luxus-Erwartungen eher auf Sal und Boa Vista erfüllbar.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Kap Verde?', a: 'Nein, für DACH-Bürger ist kein Visum im Voraus nötig. Bei der Einreise wird ein Ankunftsvisum (EASE) ausgestellt.' },
      { q: 'Wie lange dauert der Flug nach Kap Verde?', a: 'Von Wien oder München beträgt die Flugzeit nach Sal oder Boa Vista ca. 5,5–6 Stunden.' },
      { q: 'Wann ist die beste Reisezeit für Kap Verde?', a: 'Das ganze Jahr über! Temperaturen bleiben konstant bei 24–28 °C. November bis Juni ist die trockenere Saison – ideal für Strandurlaub.' },
      { q: 'Welche Währung gilt auf Kap Verde?', a: 'Der Cabo Verde Escudo (CVE) – an den Euro gebunden. Wechselkurs ca. 110 CVE pro Euro.' },
      { q: 'Ist Kap Verde für Familien geeignet?', a: 'Ja, besonders die Insel Sal mit ruhigem Wasser und flachen Stränden ist sehr familienfreundlich.' },
    ],
    poiSearch: 'Sal Kapverden',
  },
  {
    id: 'jordanien',
    file: 'jordanien.html',
    type: 'destination',
    icon: '🇯🇴',
    nameDe: 'Jordanien',
    title: 'Urlaub in Jordanien – Petra, Wadi Rum & Totes Meer | JetztBuchbar.de',
    description: 'Jordanien Urlaub 2026 buchen: Petra, Wadi Rum, Totes Meer, Aqaba. Antike Wunder, Wüstenlandschaften und Bademöglichkeiten.',
    h1Parts: ['Urlaub in', 'Jordanien'],
    heroSub: 'Das rosarote Felsenstadt Petra, die Wüste Wadi Rum und das Tote Meer – Jordanien vereint antike Wunder und Naturspektakel.',
    wikiSearch: 'Jordanien',
    climateKey: 'jordanien',
    countryKey: 'jordanien',
    tips: [
      'DACH-Bürger können ein Visum bei der Ankunft (Visa on Arrival) kaufen – ca. 40 USD. Alternativ online beantragen.',
      'Jordan Pass kaufen: Das Kombiticket enthält Visum + Eintritt zu Petra und 40 weiteren Sehenswürdigkeiten.',
      'Beste Reisezeit: März bis Mai und September bis November mit angenehmen 20–28 °C.',
      'Beachte die konservative Kultur: Schultern und Knie bedecken, besonders in Amman und Moscheen.',
      'Das Tote Meer liegt 430 m unter dem Meeresspiegel – das salzigste natürliche Gewässer der Welt. Nicht zu verpassen!',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Jordanien?', a: 'Ja, aber DACH-Bürger können es bequem bei der Ankunft (Visa on Arrival, ca. 40 USD) oder online kaufen. Der Jordan Pass enthält das Visum bereits.' },
      { q: 'Wie lange dauert der Flug nach Jordanien?', a: 'Von Wien oder München beträgt die Flugzeit nach Amman ca. 4–4,5 Stunden Direktflug.' },
      { q: 'Was kostet der Eintritt nach Petra?', a: 'Ein Tagesticket kostet ca. 50 JOD (ca. 65 €). Der Jordan Pass ist günstiger, wenn man mehrere Sehenswürdigkeiten besucht.' },
      { q: 'Welche Währung gilt in Jordanien?', a: 'Der Jordanische Dinar (JOD) – eine der stabilsten Währungen der Region. Ca. 0,77 JOD pro Euro (JOD ist stärker als der Euro).' },
      { q: 'Ist Jordanien sicher für Touristen?', a: 'Jordanien gilt als eines der stabilsten und sichersten Länder im Nahen Osten und empfängt jährlich Millionen Touristen.' },
    ],
    poiSearch: 'Petra Jordanien',
  },
];

// ── City pages ────────────────────────────────────────────────────────────────

const CITY_PAGES = [
  // Türkei
  { id: 'antalya', file: 'antalya.html', parent: 'Türkei', parentFile: 'tuerkei.html', icon: '🌊', nameDe: 'Antalya', title: 'Urlaub in Antalya – Die türkische Riviera | JetztBuchbar.de', description: 'Antalya Urlaub 2026: Strände, All-Inclusive-Resorts und die historische Altstadt Kaleiçi. Beste Angebote für DACH-Reisende.', h1Parts: ['Urlaub in', 'Antalya'], heroSub: 'Türkisblaues Meer, goldene Strände und eine 2000 Jahre alte Altstadt – Antalya ist das Herz der türkischen Riviera.', wikiSearch: 'Antalya', climateKey: 'antalya', tips: ['All-Inclusive-Resorts in Belek und Lara bieten top Qualität zum günstigen Preis.', 'Die Altstadt Kaleiçi mit dem Hadrianstor ist ein Muss – besonders abends sehr atmosphärisch.', 'Antalya-Flughafen ist einer der meistfrequentierten der Türkei – viele Direktflüge aus DACH.', 'Düden-Wasserfall und Köprülü-Canyon für Naturliebhaber und Aktivurlauber empfohlen.', 'Viele Resorts bieten kostenlose Kinderbetreuung – ideal für Familien.'], faqs: [{ q: 'Wann ist die beste Reisezeit für Antalya?', a: 'April bis Oktober. Hochsaison Juli/August mit bis zu 40 °C. Mai/Juni und September/Oktober angenehmer.' }, { q: 'Wie weit ist das Stadtzentrum vom Strand?', a: 'Je nach Hotel 5–30 Minuten. Die Resorts in Lara, Belek und Kemer liegen direkt am Meer.' }, { q: 'Gibt es Direktflüge von Wien nach Antalya?', a: 'Ja, Austrian Airlines, TUI und Charterfluggesellschaften fliegen in der Saison direkt nach Antalya (ca. 2,5 Stunden).' }, { q: 'Ist Antalya familienfreundlich?', a: 'Sehr. Riesige Resorts mit Wasserparks, Kinderbetreuung und Aquaparks machen Antalya zu einem Top-Familienziel.' }, { q: 'Was kostet All-Inclusive in Antalya?', a: 'Pro Person ab ca. 400–600 € für 7 Nächte All-Inclusive, je nach Hotel und Saison.' }], poiSearch: 'Antalya' },
  { id: 'bodrum', file: 'bodrum.html', parent: 'Türkei', parentFile: 'tuerkei.html', icon: '⛵', nameDe: 'Bodrum', title: 'Urlaub in Bodrum – Ägäis, Yachten & Nachtleben | JetztBuchbar.de', description: 'Bodrum Urlaub 2026: weiße Häuser, Buchten, Nachtleben und Yacht-Chartern an der Türkischen Ägäis.', h1Parts: ['Urlaub in', 'Bodrum'], heroSub: 'Weiß getünchte Häuser, smaragdgrüne Buchten und eine lebhafte Partyszene – Bodrum ist das St. Tropez der Türkei.', wikiSearch: 'Bodrum', climateKey: 'bodrum', tips: ['Bodrum Castle (Schloss St. Peter) und das Unterwasserarchäologiemuseum nicht verpassen.', 'Bootstrip zu den Buchten (Akyarlar, Karaincir) unbedingt machen – am schönsten per Gulet-Boot.', 'Bodrum Bazaar für lokale Einkäufe: Gewürze, Keramik, Lederwaren.', 'Das Nachtleben in Bodrum ist legendär – Halikarnas Open Air Club ist weltbekannt.', 'Für Ruhesuchende: Güvercinlik und Torba sind ruhigere Alternativen zum pulsierenden Zentrum.'], faqs: [{ q: 'Wann ist die beste Reisezeit für Bodrum?', a: 'Juni bis September. Bodrum ist bekannt für seinen Wind (Meltemi) – ideal zum Segeln, aber gelegentlich unangenehm am Strand.' }, { q: 'Gibt es Direktflüge nach Bodrum?', a: 'Ja, Bodrum Milas Airport hat in der Saison Direktverbindungen aus Wien, München und Zürich.' }, { q: 'Ist Bodrum teurer als andere Türkei-Ziele?', a: 'Ja, Bodrum ist exklusiver und teurer als Antalya oder Alanya – dafür glamouröser und internationaler.' }, { q: 'Welche Strände sind in Bodrum am besten?', a: 'Bitez für Windsurfer, Camel Beach für Familien, und Gümbet für Partytouristen.' }, { q: 'Kann man von Bodrum nach Griechenland?', a: 'Ja! Mit der Fähre ist Kos und Rhodos von Bodrum aus in 30–60 Minuten erreichbar.' }], poiSearch: 'Bodrum' },
  // Griechenland
  { id: 'kreta-stadt', file: 'kreta-urlaub.html', parent: 'Griechenland', parentFile: 'griechenland.html', icon: '🏔️', nameDe: 'Kreta', title: 'Urlaub auf Kreta – Heraklion, Chania & Strände | JetztBuchbar.de', description: 'Kreta Urlaub 2026: Heraklion, Chania, Samaria-Schlucht, Elafonisi. Griechenlands größte Insel entdecken.', h1Parts: ['Urlaub auf', 'Kreta'], heroSub: "Griechenlands größte Insel bietet alles: minoische Paläste, schneeweiße Strände und eine herausragende Küche.", wikiSearch: 'Kreta', climateKey: 'kreta', tips: ['Die Samaria-Schlucht ist eine der längsten Europas – für die 16 km Wanderung früh starten.', 'Elafonisi im Südwesten: der rosafarbene Strand mit türkisblauem Wasser ist einzigartig in Europa.', 'Knossos – der minoische Palast bei Heraklion – ist Pflicht für Geschichtsinteressierte.', 'Frische Meeresfrüchte in Elounda oder Agios Nikolaos – weit günstiger als auf kleineren Inseln.', 'Mietwagen empfohlen: Kreta ist groß, die schönsten Teile liegen weit auseinander.'], faqs: [{ q: 'Wie komme ich nach Kreta?', a: 'Direktflüge nach Heraklion (HER) oder Chania (CHQ) von Wien oder München in ca. 2,5–3 Stunden.' }, { q: 'Welche Seite Kretas ist schöner – Nord oder Süd?', a: 'Norden für Komfort und Resorts, Süden für wilde Natur und einsame Strände. Am besten beide erleben.' }, { q: 'Ist Kreta für Familien geeignet?', a: 'Sehr. Viele familienfreundliche Resorts, ruhige Buchten und Kinderanimation. Besonders Hersonissos und Malia empfohlen.' }, { q: 'Was kostet Urlaub auf Kreta?', a: 'Günstiger als viele andere griechische Inseln. 7 Nächte Halbpension ab ca. 500–700 € pro Person.' }, { q: 'Wann hat Kreta Hauptsaison?', a: 'Juli und August sind vollbesetzt. Mai, Juni und September sind ideal mit weniger Touristen und niedrigeren Preisen.' }], poiSearch: 'Heraklion Kreta' },
  { id: 'santorini-stadt', file: 'santorini-urlaub.html', parent: 'Griechenland', parentFile: 'griechenland.html', icon: '🌅', nameDe: 'Santorini', title: 'Urlaub auf Santorini – Oia, Sonnenuntergang & Vulkan | JetztBuchbar.de', description: 'Santorini Urlaub 2026: Oia, Fira, Caldera, Vulkantour. Das romantischste Reiseziel Griechenlands.', h1Parts: ['Urlaub auf', 'Santorini'], heroSub: 'Weiß-blaue Kykladen-Architektur, spektakuläre Caldera und der berühmteste Sonnenuntergang der Welt – Santorini verzaubert jeden.', wikiSearch: 'Santorin', climateKey: 'santorini', tips: ['Den Sonnenuntergang von Oia erleben – frühzeitig einen Platz sichern, es wird voll.', 'Mit dem Boot zur Caldera und zum aktiven Vulkan – unvergessliches Erlebnis.', 'Akrotiri: die minoische Ausgrabungsstätte ist das "Pompeji Griechenlands".', 'Santorini-Wein probieren: Assyrtiko-Weißwein wächst auf der vulkanischen Erde und ist weltweit einzigartig.', 'Preise sind hoch – früh buchen und für Restaurants Reservierungen machen.'], faqs: [{ q: 'Wie komme ich nach Santorini?', a: 'Direktflug nach Thira (JTR) ca. 2,5 Stunden ab Wien/München, oder Fähre von Athen (Piräus) in 5–8 Stunden.' }, { q: 'Ist Santorini geeignet für Familien?', a: 'Eher nein – Santorini ist romantisch und auf Paare/Honeymoon ausgerichtet. Wenig Strandoptionen, viele Treppen.' }, { q: 'Wann ist die beste Reisezeit für Santorini?', a: 'Mai bis Oktober. Außerhalb der Hochsaison (Juli/August) sind Preise günstiger und weniger überfüllt.' }, { q: 'Was kostet eine Übernachtung in Oia?', a: 'Oia gehört zu den teuersten Reisezielen Griechenlands – Zimmer ab 150 € pro Nacht in der Hauptsaison, Suiten mit Caldera-Blick bis 1000 €+.' }, { q: 'Warum sind die Häuser in Santorini weiß und blau?', a: 'Weiß reflektiert die Sommerhitze, und Blau war historisch günstigste Farbe. Heute ist es gesetzlich vorgeschrieben für das Erscheinungsbild der Insel.' }], poiSearch: 'Santorini' },
];

// ── Reisezeit pages ───────────────────────────────────────────────────────────

const REISEZEIT_PAGES = [
  { id: 'reisezeit-tuerkei', file: 'beste-reisezeit-tuerkei.html', nameDe: 'Türkei', destFile: 'tuerkei.html', icon: '🇹🇷', title: 'Beste Reisezeit Türkei 2026 – Wann reisen? | JetztBuchbar.de', description: 'Wann ist die beste Reisezeit für die Türkei? Klima, Temperaturen und Tipps für jede Jahreszeit.' },
  { id: 'reisezeit-spanien', file: 'beste-reisezeit-spanien.html', nameDe: 'Spanien', destFile: 'spanien.html', icon: '🇪🇸', title: 'Beste Reisezeit Spanien 2026 – Mallorca, Teneriffa & mehr | JetztBuchbar.de', description: 'Wann ist die beste Reisezeit für Spanien? Klimatabelle, Temperaturen und Tipps nach Region.' },
  { id: 'reisezeit-griechenland', file: 'beste-reisezeit-griechenland.html', nameDe: 'Griechenland', destFile: 'griechenland.html', icon: '🇬🇷', title: 'Beste Reisezeit Griechenland 2026 | JetztBuchbar.de', description: 'Wann ist die beste Reisezeit für Griechenland? Kreta, Santorini und die Inseln im Klimavergleich.' },
  { id: 'reisezeit-aegypten', file: 'beste-reisezeit-aegypten.html', nameDe: 'Ägypten', destFile: 'aegypten.html', icon: '🇪🇬', title: 'Beste Reisezeit Ägypten 2026 – Hurghada & Sharm | JetztBuchbar.de', description: 'Wann ist die beste Reisezeit für Ägypten? Klimavergleich Hurghada, Sharm el-Sheikh und Kairo.' },
  { id: 'reisezeit-marokko', file: 'beste-reisezeit-marokko.html', nameDe: 'Marokko', destFile: 'marokko.html', icon: '🇲🇦', title: 'Beste Reisezeit Marokko 2026 | JetztBuchbar.de', description: 'Wann nach Marokko reisen? Klimatabelle Marrakesch, Agadir und die beste Jahreszeit.' },
  { id: 'reisezeit-dubai', file: 'beste-reisezeit-dubai.html', nameDe: 'Dubai', destFile: 'dubai.html', icon: '🇦🇪', title: 'Beste Reisezeit Dubai 2026 – Oktober bis April ideal | JetztBuchbar.de', description: 'Wann nach Dubai reisen? Klimatable, Temperaturen und Tipps für den perfekten Zeitpunkt.' },
  { id: 'reisezeit-portugal', file: 'beste-reisezeit-portugal.html', nameDe: 'Portugal', destFile: 'portugal.html', icon: '🇵🇹', title: 'Beste Reisezeit Portugal 2026 – Algarve & Lissabon | JetztBuchbar.de', description: 'Wann nach Portugal reisen? Klimavergleich Algarve, Lissabon und Porto nach Monaten.' },
  { id: 'reisezeit-malta', file: 'beste-reisezeit-malta.html', nameDe: 'Malta', destFile: 'malta.html', icon: '🇲🇹', title: 'Beste Reisezeit Malta 2026 | JetztBuchbar.de', description: 'Wann nach Malta reisen? Klimatabelle und Empfehlungen für den besten Urlaubszeitpunkt.' },
];

// ── Thema pages ───────────────────────────────────────────────────────────────

const THEMA_PAGES = [
  {
    id: 'urlaub-mit-kindern',
    file: 'urlaub-mit-kindern.html',
    icon: '👨‍👩‍👧‍👦',
    title: 'Urlaub mit Kindern 2026 – Die besten Familienziele | JetztBuchbar.de',
    description: 'Die besten Familienreiseziele 2026: Türkei, Spanien, Griechenland. Tipps für Urlaub mit Kindern und Top-Resorts.',
    h1Parts: ['Urlaub mit', 'Kindern'],
    heroSub: 'Familienurlaub perfekt geplant: die besten kinderfreundlichen Resorts, Strände und Aktivitäten für unvergessliche Ferien.',
    intro: 'Urlaub mit Kindern erfordert besondere Planung: flache Strände, gute Kinderbetreuung, abwechslungsreiche Aktivitäten und sichere Unterkünfte. Diese Seite hilft Ihnen, das ideale Familienziel zu finden.',
    tips: [
      'All-Inclusive-Resorts mit Kinderclub sind ideal für Familien – Eltern können sich entspannen, Kinder werden betreut.',
      'Flache Sandstrände ohne Wellen bevorzugen: Lara Beach (Antalya), Side oder Mallorca sind ideal für kleine Kinder.',
      'Außerhalb der Hochsaison reisen (Juni oder September) – weniger überfüllt, günstiger, angenehmer für Kinder.',
      'Snacks und Lieblingsspielzeug einpacken – lange Flüge und Wartezeiten werden mit Vorbereitung einfacher.',
      'Kinderreisepass rechtzeitig beantragen – mindestens 6 Wochen vor der Reise beim Standesamt.',
    ],
    faqs: [
      { q: 'Welche Ziele sind am besten für Urlaub mit kleinen Kindern?', a: 'Antalya, Side und Alanya in der Türkei sowie Mallorca bieten flache Strände, große Resorts mit Animation und sind von DACH gut erreichbar.' },
      { q: 'Ab welchem Alter können Kinder in den Flugzeug?', a: 'Babys ab 1 Woche sind flugfähig, aber Ärzte empfehlen zu warten bis das Kind 4–6 Wochen alt ist. Ab 2 Jahren benötigen Kinder einen eigenen Sitzplatz.' },
      { q: 'Welche Impfungen brauchen Kinder für Auslandsreisen?', a: 'Für EU-Reiseziele meist keine Pflichtimpfungen. Für Ägypten, Marokko oder Tunesien Hepatitis A und Typhus empfohlen – Kinderarzt konsultieren.' },
      { q: 'Was ist der Unterschied zwischen Kinderclub und Animation?', a: 'Kinderclub bietet professionelle Betreuung für bestimmte Altersgruppen. Animation ist Unterhaltung für alle Altersgruppen (Shows, Spiele, Sport).' },
      { q: 'Wie viel Gepäck darf ein Kind mitbringen?', a: 'Je nach Airline bekommen Kinder ab 2 Jahren dasselbe Freigepäck wie Erwachsene. Babys unter 2 Jahren haben oft kein oder reduziertes Freigepäck.' },
    ],
    destinations: ['Türkei', 'Spanien', 'Griechenland', 'Bulgarien'],
  },
  {
    id: 'flitterwochen',
    file: 'flitterwochen.html',
    icon: '💑',
    title: 'Flitterwochen & Hochzeitsreisen 2026 – Romantische Ziele | JetztBuchbar.de',
    description: 'Traumhafte Flitterwochen-Ziele 2026: Santorini, Malediven, Dubai, Bali. Tipps und Inspiration für Ihre Hochzeitsreise.',
    h1Parts: ['Flitterwochen &', 'Hochzeitsreisen'],
    heroSub: 'Ihr schönster Urlaub verdient das romantischste Ziel. Entdecken Sie die beliebtesten Flitterwochen-Destinationen 2026.',
    intro: 'Flitterwochen sind die vielleicht wichtigste Reise des Lebens. Von Santorinis Sonnenuntergängen bis zu Dubais Luxushotels – wir helfen Ihnen, die perfekte Honeymoon-Destination zu finden.',
    tips: [
      'Frühzeitig buchen: Die besten Honeymoon-Suiten in Santorini und Dubai sind oft 6–12 Monate im Voraus ausgebucht.',
      'Als Flitterwochen-Paar beim Einchecken mitteilen – viele Hotels bieten kostenlose Upgrades oder Willkommensgeschenke.',
      'Santorini von Mai bis Oktober, Malediven und Dubai Oktober bis April – Reisezeit dem Ziel anpassen.',
      'Privat-Pool-Villa oder Overwater-Bungalow für ultimative Privatsphäre und Romantik.',
      'Dinner bei Sonnenuntergang reservieren – besonders in Oia (Santorini) oder auf dem Burj Khalifa (Dubai).',
    ],
    faqs: [
      { q: 'Welches ist das romantischste Reiseziel für Flitterwochen?', a: 'Santorini gilt weltweit als romantischstes Reiseziel. Dubai für Luxus, Bali für Natur und Spiritualität, Malediven für Overwater-Bungalows.' },
      { q: 'Wie viel sollte man für Flitterwochen budgetieren?', a: 'Von 2.000 € (Santorini/Zypern) bis 10.000 €+ (Malediven/Bali). Das richtige Budget hängt von Destination und Luxuslevel ab.' },
      { q: 'Wann sollte man Flitterwochen buchen?', a: 'Mindestens 6–12 Monate vor der Hochzeit. Hochzeiten finden oft im Sommer statt – Hochsaison-Hotels früh reservieren.' },
      { q: 'Was sollte man in die Flitterwochen-Planung einbeziehen?', a: 'Visumsanforderungen, Reiseversicherung, romantische Aktivitäten (privates Dinner, Bootstouren), besondere Unterkünfte und Überraschungen.' },
      { q: 'Gibt es spezielle Flitterwochen-Pakete bei Hotels?', a: 'Ja, viele Hotels bieten Honeymoon-Pakete: Champagner bei Ankunft, Blumendekoration, Spa-Gutscheine und spezielle Dinner-Reservierungen.' },
    ],
    destinations: ['Santorini', 'Dubai', 'Zypern', 'Portugal'],
  },
  {
    id: 'last-minute',
    file: 'last-minute-urlaub.html',
    icon: '⚡',
    title: 'Last Minute Urlaub 2026 – Günstig spontan reisen | JetztBuchbar.de',
    description: 'Last Minute Urlaub günstig buchen: Türkei, Spanien, Griechenland, Ägypten. Die besten Tipps für spontanes Reisen.',
    h1Parts: ['Last Minute', 'Urlaub'],
    heroSub: 'Spontan verreisen und dabei richtig sparen – mit den richtigen Tipps sind Last-Minute-Angebote oft die günstigsten des Jahres.',
    intro: 'Last-Minute-Urlaub bedeutet nicht schlechtere Qualität – oft ist es das Gegenteil. Hotels und Reiseveranstalter senken kurz vor Abreise die Preise drastisch, um freie Kapazitäten zu füllen.',
    tips: [
      'Beste Last-Minute-Deals gibt es 7–14 Tage vor Abreise – besonders für All-Inclusive in Türkei und Ägypten.',
      'Flexibel bleiben: Wer Ziel und Datum offen lässt, findet die günstigsten Angebote.',
      'Werktags früh morgens nach Angeboten suchen – neue Deals werden oft in den frühen Morgenstunden eingestellt.',
      'Handgepäck-only Angebote sparen nochmals 20–40 € pro Person.',
      'Reiseversicherung auch bei Last-Minute-Buchungen abschließen – besonders für Krankenversicherung im Ausland.',
    ],
    faqs: [
      { q: 'Wie weit im Voraus ist Last-Minute?', a: 'Last-Minute gilt typischerweise für Reisen, die 1–4 Wochen vor Abreise gebucht werden. Die günstigsten Angebote oft 7–10 Tage vor Reisebeginn.' },
      { q: 'Welche Ziele sind für Last-Minute am besten?', a: 'Türkei (Antalya, Alanya), Ägypten (Hurghada), Spanien (Mallorca, Teneriffa) – große Resorts mit vielen Betten haben oft Last-Minute-Verfügbarkeit.' },
      { q: 'Ist Last-Minute wirklich günstiger?', a: 'Ja, oft 30–50 % günstiger als Früh-Buchung. Aber Zimmerauswahl und Lage können eingeschränkt sein.' },
      { q: 'Brauche ich eine Reiseversicherung bei Last-Minute?', a: 'Unbedingt. Besonders Auslandskrankenversicherung und Reiserücktrittsversicherung sind wichtig – auch bei kurzfristiger Buchung.' },
      { q: 'Kann ich Last-Minute auch für Familien buchen?', a: 'Ja, aber Familienzimmer/-suiten sind früher ausgebucht. Bei Familien empfehlen wir daher maximal 2–3 Wochen Vorlaufzeit.' },
    ],
    destinations: ['Türkei', 'Ägypten', 'Spanien', 'Bulgarien'],
  },
  {
    id: 'all-inclusive',
    file: 'all-inclusive-urlaub.html',
    icon: '🍹',
    title: 'All Inclusive Urlaub 2026 – Beste Resorts & Ziele | JetztBuchbar.de',
    description: 'All-Inclusive-Urlaub 2026 günstig buchen: Türkei, Spanien, Ägypten. Die besten All-Inclusive-Resorts für jeden Geldbeutel.',
    h1Parts: ['All Inclusive', 'Urlaub'],
    heroSub: 'Sorglos genießen ohne ständig ans Portemonnaie denken – All-Inclusive-Urlaub ist die entspannteste Art zu reisen.',
    intro: 'All-Inclusive bedeutet: Unterkunft, alle Mahlzeiten, Snacks und Getränke (meist auch Alkohol) sowie viele Aktivitäten im Preis inbegriffen. Besonders für Familien und in der Türkei extrem beliebt.',
    tips: [
      'Antalya und Alanya bieten das beste All-Inclusive-Preis-Leistungs-Verhältnis in Europa – Qualität für kleines Geld.',
      'Ultra All-Inclusive vs. Standard: "Ultra AI" schließt auch Premium-Spirituosen, À-la-carte-Restaurants und Ausflüge ein.',
      'Ressort-Lage prüfen: direkt am Strand oder mit Transfer? Stromanbieter auf der Website des Resorts ansehen.',
      'Animationsprogramm und Kinderclub in der Hotelbeschreibung überprüfen – je nach Reisegruppe wichtig.',
      'Reiseversicherung abschließen: Bei All-Inclusive-Buchungen ist die Gesamtsumme hoch – Stornoschutz lohnt sich.',
    ],
    faqs: [
      { q: 'Was ist im All-Inclusive-Urlaub inklusive?', a: 'Unterkunft, alle Mahlzeiten (Frühstück, Mittagessen, Abendessen), Snacks zwischendurch, lokale Getränke (Alkohol und alkoholfrei). Extras je nach Hotel.' },
      { q: 'Welches Land bietet das beste All-Inclusive?', a: 'Die Türkei (besonders Antalya) gilt als Weltmeister im All-Inclusive-Segment: sehr hohe Qualität zu günstigen Preisen.' },
      { q: 'Was ist Ultra All-Inclusive?', a: 'Ultra AI ist die Premium-Stufe: Premium-Getränke aller Marken, mehrere À-la-carte-Restaurants, Spa-Nutzung und oft auch Ausflüge oder Wassersport inklusive.' },
      { q: 'Lohnt sich All-Inclusive für Paare ohne Kinder?', a: 'Ja, besonders wenn man im Hotel entspannen will. Wer lieber lokale Restaurants entdeckt, spart mit Halbpension und profitiert mehr vom Ort.' },
      { q: 'Wie bucht man günstig All-Inclusive?', a: 'Frühbucher-Rabatte (5–7 Monate vor Abreise) oder Last-Minute (1–2 Wochen). Vergleichsportale und direkte Anfragen beim Reisebüro empfohlen.' },
    ],
    destinations: ['Türkei', 'Ägypten', 'Spanien', 'Bulgarien'],
  },
];

// ── All pages combined ────────────────────────────────────────────────────────

const ALL_PAGES = [
  ...DESTINATION_PAGES,
  ...CITY_PAGES,
  ...REISEZEIT_PAGES,
  ...THEMA_PAGES,
];

module.exports = {
  DESTINATION_PAGES,
  CITY_PAGES,
  REISEZEIT_PAGES,
  THEMA_PAGES,
  ALL_PAGES,
};
