'use strict';

/**
 * Page definitions — the full queue of pages to generate.
 * Each entry describes one output HTML file.
 */

// ── Destination pages (country level) ────────────────────────────────────────

const DESTINATION_PAGES = [
  {
    id: 'tuerkei',
    file: 'tuerkei.html',
    type: 'destination',
    icon: '🇹🇷',
    nameDe: 'Türkei',
    title: 'Urlaub in der Türkei – Antalya, Istanbul & Bodrum | JetztBuchbar.de',
    description: 'Türkei Urlaub 2026 günstig buchen: Antalya, Istanbul, Bodrum, Alanya. Beste Reisezeit, Tipps und All-Inclusive-Angebote für DACH-Reisende.',
    h1Parts: ['Urlaub in der', 'Türkei'],
    heroSub: 'Türkisblaues Meer, goldene Sandstrände und jahrtausendealte Geschichte – die Türkei ist eines der beliebtesten Reiseziele für DACH-Reisende.',
    wikiSearch: 'Türkei',
    climateKey: 'antalya',
    countryKey: 'tuerkei',
    tips: [
      'Kein Visum erforderlich für DACH-Bürger bei Aufenthalten bis 90 Tage – ein gültiger Reisepass genügt.',
      'Beste Reisezeit für Badeurlaub: Mai bis Oktober. Juli/August am heißesten (35–40 °C), September/Oktober ideal.',
      'All-Inclusive-Resorts in Antalya, Belek und Side bieten hervorragendes Preis-Leistungs-Verhältnis.',
      'Turkish Lira (TRY) im Land wechseln – Kurse am Flughafen sind meist schlechter als in der Stadt.',
      'Istanbul lohnt immer: Bosporus-Kreuzfahrt, Hagia Sophia, Großer Basar und die Gewürzstraße sollten nicht fehlen.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für die Türkei?', a: 'Nein. Bürger aus Deutschland, Österreich und der Schweiz können bis zu 90 Tage visumfrei in die Türkei einreisen. Ein gültiger Reisepass ist erforderlich.' },
      { q: 'Wie lange dauert der Flug in die Türkei?', a: 'Von Wien oder München nach Antalya dauert ein Direktflug ca. 2,5–3 Stunden, nach Istanbul ca. 2,5 Stunden.' },
      { q: 'Welche Währung gilt in der Türkei?', a: 'Die Türkische Lira (TRY). Euro und USD werden in Touristenzentren oft akzeptiert, aber Lira ist günstiger. Geldwechsel in der Türkei ist vorteilhafter als vorab.' },
      { q: 'Ist die Türkei für Familien geeignet?', a: 'Absolut. Antalya gilt als eines der familienfreundlichsten Reiseziele Europas mit riesigen Resorts, Wasserparks und Kinderbetreuung.' },
      { q: 'Was sind die beliebtesten Strände in der Türkei?', a: 'Lara Beach und Konyaaltı in Antalya, Ölüdeniz (Blaue Lagune) in Fethiye, Alaçatı auf Çeşme und die Bodrum-Buchten an der Ägäisküste.' },
    ],
    poiSearch: 'Antalya',
  },
  {
    id: 'spanien',
    file: 'spanien.html',
    type: 'destination',
    icon: '🇪🇸',
    nameDe: 'Spanien',
    title: 'Urlaub in Spanien – Mallorca, Barcelona & Kanaren | JetztBuchbar.de',
    description: 'Spanien Urlaub 2026 günstig buchen: Mallorca, Teneriffa, Barcelona, Costa del Sol. Beste Reisezeit, Tipps und Angebote.',
    h1Parts: ['Urlaub in', 'Spanien'],
    heroSub: 'Sonnige Strände, lebendige Städte und vielfältige Kulinarik – Spanien ist das vielseitigste Reiseziel Europas.',
    wikiSearch: 'Spanien',
    climateKey: 'mallorca',
    countryKey: 'spanien',
    tips: [
      'Als EU-Bürger (Deutschland, Österreich) reisen Sie ohne Visum und nur mit dem Personalausweis ein.',
      'Mallorca und Teneriffa eignen sich für Ganzjahresurlaub – die Kanaren bieten auch im Winter milde Temperaturen (20–24 °C).',
      'Barcelona, Madrid und Sevilla sind ideal für Städtereisen mit Architektur, Flamenco und erstklassiger Gastronomie.',
      'Siesta beachten: Viele Geschäfte und Restaurants schließen zwischen 14–17 Uhr, dafür ist bis Mitternacht geöffnet.',
      'Frühzeitig buchen für Mallorca im Sommer – Juli/August sind extrem beliebt und teuer.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Spanien?', a: 'Nein. Als EU-Bürger (Deutschland, Österreich) oder mit Schweizer Pass reisen Sie visumfrei ein. Ein Personalausweis oder Reisepass genügt.' },
      { q: 'Wie lange ist der Flug nach Spanien?', a: 'Nach Mallorca ca. 2 Stunden, nach Teneriffa ca. 4,5 Stunden, nach Barcelona ca. 2 Stunden – alles von Wien oder München.' },
      { q: 'Welche Währung gilt in Spanien?', a: 'Der Euro (€). Kreditkarten werden fast überall akzeptiert.' },
      { q: 'Wann ist die beste Reisezeit für Spanien?', a: 'Mai/Juni und September/Oktober für angenehme Temperaturen (22–28 °C) ohne Hochsommerhitze. Die Kanaren funktionieren das ganze Jahr.' },
      { q: 'Was sind die besten Reiseziele in Spanien?', a: 'Mallorca für Strand & Aktivurlaub, Barcelona für Kultur & Gastronomie, Teneriffa für Familienurlaub, Ibiza für Partytourismus und die Costa del Sol für klassischen Badeurlaub.' },
    ],
    poiSearch: 'Barcelona',
  },
  {
    id: 'griechenland',
    file: 'griechenland.html',
    type: 'destination',
    icon: '🇬🇷',
    nameDe: 'Griechenland',
    title: 'Urlaub in Griechenland – Kreta, Santorini & Rhodos | JetztBuchbar.de',
    description: 'Griechenland Urlaub 2026 günstig buchen: Kreta, Santorini, Rhodos, Korfu. Beste Reisezeit, Tipps und Angebote für DACH-Reisende.',
    h1Parts: ['Urlaub in', 'Griechenland'],
    heroSub: 'Strahlend weiße Kirchen, tiefblaues Meer und antike Tempel – Griechenland verbindet Mythos, Strand und unvergessliche Inselerlebnisse.',
    wikiSearch: 'Griechenland',
    climateKey: 'kreta',
    countryKey: 'griechenland',
    tips: [
      'Als EU-Bürger (Deutschland, Österreich) ist kein Visum erforderlich. Einreise nur mit Personalausweis.',
      'Beste Reisezeit: Mai/Juni und September/Oktober – angenehme Temperaturen, weniger Touristen als im August.',
      'Santorini und Mykonos sind teuer – Rhodos, Kreta und Korfu bieten ein besseres Preis-Leistungs-Verhältnis.',
      'Frisches Olivenöl, Feta und Meeresfrüchte sind griechische Spezialitäten, die man unbedingt probieren sollte.',
      'Der Meltemi-Wind im Sommer kann auf Kykladen-Inseln stark sein – für Segler top, für Strandgänger manchmal lästig.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Griechenland?', a: 'Nein. Als Bürger aus Deutschland oder Österreich reisen Sie als EU-Bürger ohne Visum ein. Schweizer benötigen nur den Reisepass.' },
      { q: 'Wie lange dauert der Flug nach Griechenland?', a: 'Nach Kreta ca. 2,5–3 Stunden, nach Santorini oder Rhodos ca. 2,5 Stunden – alles Direktflüge ab Wien oder München.' },
      { q: 'Welche Währung gilt in Griechenland?', a: 'Der Euro (€). Auf kleineren Inseln empfiehlt sich Bargeld – nicht überall werden Karten akzeptiert.' },
      { q: 'Welche griechische Insel ist am schönsten?', a: 'Das kommt auf die Vorlieben an: Santorini für Romantik & Fotos, Kreta für Vielfalt & Natur, Mykonos für Nightlife, Rhodos für Geschichte & Strand.' },
      { q: 'Wann ist die beste Reisezeit für Griechenland?', a: 'Mai, Juni und September/Oktober. Im Juli und August ist es sehr heiß (32–38 °C) und voll. Für Santorini am besten April/Mai oder Oktober.' },
    ],
    poiSearch: 'Athen',
  },
  {
    id: 'aegypten',
    file: 'aegypten.html',
    type: 'destination',
    icon: '🇪🇬',
    nameDe: 'Ägypten',
    title: 'Urlaub in Ägypten – Hurghada, Sharm el-Sheikh & Nil | JetztBuchbar.de',
    description: 'Ägypten Urlaub 2026 günstig buchen: Hurghada, Sharm el-Sheikh, Kairo, Luxor. Beste Reisezeit, Tipps und All-Inclusive-Angebote.',
    h1Parts: ['Urlaub in', 'Ägypten'],
    heroSub: 'Pyramiden, Pharaonentempel und traumhafte Korallenriffe im Roten Meer – Ägypten ist wo Geschichte auf Strandurlaub trifft.',
    wikiSearch: 'Ägypten',
    climateKey: 'hurghada',
    countryKey: 'aegypten',
    tips: [
      'Ein Visum ist erforderlich – erhältlich bei der Ankunft (ca. 25 USD) oder vorab als E-Visum online.',
      'Beste Reisezeit: Oktober bis April mit 20–30 °C. Sommer (Juni–August) mit 40+ °C an der Küste besser meiden.',
      'Trinkwasser nur aus verschlossenen Flaschen – Leitungswasser ist für Touristen nicht geeignet.',
      'Feilschen auf den Basaren ist Tradition und macht Spaß – immer freundlich und mit Humor.',
      'Tagesausflug zu den Pyramiden von Gizeh von Hurghada oder Sharm ist per Flug oder Bus möglich.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Ägypten?', a: 'Ja. Deutsche, Österreicher und Schweizer benötigen ein Visum. Es kann bei der Ankunft (ca. 25 USD) oder vorab als E-Visum (evisa.gov.eg) beantragt werden.' },
      { q: 'Wie lange dauert der Flug nach Ägypten?', a: 'Von Wien oder München nach Hurghada oder Sharm el-Sheikh ca. 4 Stunden Direktflug. Nach Kairo ca. 3,5 Stunden.' },
      { q: 'Welche Währung gilt in Ägypten?', a: 'Das Ägyptische Pfund (EGP). Wechseln Sie Geld an offiziellen Wechselstuben – Straßenwechsler sind illegal und unsicher.' },
      { q: 'Ist Ägypten für Familien geeignet?', a: 'Ja, vor allem Hurghada mit seinen All-Inclusive-Resorts ist sehr familienfreundlich. Snorkeling, Wasserparks und Ausflüge machen es für alle Altersgruppen attraktiv.' },
      { q: 'Was sollte ich in Ägypten unbedingt sehen?', a: 'Die Pyramiden von Gizeh & Sphinx, der Ägyptische Museumsaal in Kairo, die Korallenriffe im Roten Meer, Luxor & Karnak-Tempel und eine Nilkreuzfahrt.' },
    ],
    poiSearch: 'Kairo',
  },
  {
    id: 'marokko',
    file: 'marokko.html',
    type: 'destination',
    icon: '🇲🇦',
    nameDe: 'Marokko',
    title: 'Urlaub in Marokko – Marrakesch, Agadir & mehr | JetztBuchbar.de',
    description: 'Marokko Urlaub 2026 günstig buchen: Marrakesch, Agadir, Essaouira. Beste Reisezeit, Tipps und Angebote für DACH-Reisende.',
    h1Parts: ['Urlaub in', 'Marokko'],
    heroSub: 'Orientalisches Flair, endlose Wüsten und traumhafte Atlantikstrände – Marokko ist ein Reiseziel der Gegensätze.',
    wikiSearch: 'Marokko',
    climateKey: 'marokko',
    countryKey: 'marokko',
    tips: [
      'Für DACH-Bürger ist kein Visum erforderlich – bei einer Aufenthaltsdauer bis zu 90 Tagen reicht der Reisepass.',
      'Die beste Reisezeit für Strand und Sightseeing ist März bis Mai sowie September bis November.',
      'Feilschen ist auf den Souks Tradition – aber respektvoll und mit Humor. Startpreis oft 2–3x höher als Endpreis.',
      'Frauen sollten außerhalb der Resorts die Schultern und Knie bedecken, besonders in konservativeren Städten.',
      'Trinkwasser nur aus verschlossenen Flaschen trinken – Leitungswasser ist nicht für Touristen geeignet.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Marokko?', a: 'Nein. Bürger aus Deutschland, Österreich und der Schweiz können bis zu 90 Tage visumfrei einreisen. Ein gültiger Reisepass ist erforderlich.' },
      { q: 'Wie lange ist der Flug nach Marokko?', a: 'Von Wien oder München dauert ein Direktflug nach Marrakesch oder Agadir ca. 3,5–4 Stunden.' },
      { q: 'Welche Währung gilt in Marokko?', a: 'Die offizielle Währung ist der Marokkanische Dirham (MAD). Dieser kann nicht im Ausland gekauft werden – Geldwechsel am Flughafen oder an Wechselstuben vor Ort.' },
      { q: 'Ist Marokko sicher für Touristen?', a: 'Die Haupttouristenzentren wie Marrakesch, Agadir und Fes gelten als sicher. Wie überall empfiehlt sich Aufmerksamkeit in belebten Souks wegen Taschendiebstahls.' },
      { q: 'Was sollte ich in Marokko unbedingt gesehen haben?', a: 'Djemaa el-Fna in Marrakesch, die Sahara bei Merzouga, die blaue Stadt Chefchaouen, Essaouira am Atlantik und die Königsstadt Fes.' },
    ],
    poiSearch: 'Marrakesch',
  },
  {
    id: 'tunesien',
    file: 'tunesien.html',
    type: 'destination',
    icon: '🇹🇳',
    nameDe: 'Tunesien',
    title: 'Urlaub in Tunesien – Djerba, Hammamet & mehr | JetztBuchbar.de',
    description: 'Tunesien Urlaub 2026 günstig buchen: Djerba, Hammamet, Sousse. Beste Reisezeit, Tipps und All-Inclusive-Angebote.',
    h1Parts: ['Urlaub in', 'Tunesien'],
    heroSub: 'Weißblaue Häuser, phönizische Geschichte und goldene Sandstrände am Mittelmeer – Tunesien bietet Urlaub für jeden Geldbeutel.',
    wikiSearch: 'Tunesien',
    climateKey: 'tunesien',
    countryKey: 'tunesien',
    tips: [
      'Kein Visum erforderlich für DACH-Bürger bei Aufenthalten bis zu 90 Tagen.',
      'All-Inclusive-Resorts in Djerba, Hammamet und Sousse bieten hervorragendes Preis-Leistungs-Verhältnis.',
      'Die beste Reisezeit ist April bis Juni sowie September bis Oktober – angenehme 25–30 °C ohne Hochsommerhitze.',
      'Trinkwasser nur aus Flaschen – Leitungswasser sollte nicht getrunken werden.',
      'Abends einen Hauch der Medina erleben: Tunis-Medina ist UNESCO-Welterbe und einen Tagesausflug wert.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Tunesien?', a: 'Nein. Bürger aus Deutschland, Österreich und der Schweiz reisen bis zu 90 Tage visumfrei ein.' },
      { q: 'Wie lange dauert der Flug nach Tunesien?', a: 'Von Wien oder München beträgt die Flugzeit nach Djerba oder Tunis ca. 2,5–3 Stunden Direktflug.' },
      { q: 'Ist Tunesien sicher für Touristen?', a: 'Die Touristenzentren wie Djerba, Hammamet und Sousse sind gut gesichert. Aktuelle Reisewarnungen des Außenministeriums sollten vor der Reise geprüft werden.' },
      { q: 'Welche Währung gilt in Tunesien?', a: 'Der Tunesische Dinar (TND) ist die Landeswährung. Geldwechsel am Flughafen oder in Banken empfohlen – der Dinar darf nicht ausgeführt werden.' },
      { q: 'Was sind die beliebtesten Reiseziele in Tunesien?', a: 'Djerba für Badeurlaub, Hammamet für Familien, Sousse für Aktivurlauber, und Tunis mit der UNESCO-Medina für Kulturinteressierte.' },
    ],
    poiSearch: 'Djerba',
  },
  {
    id: 'dubai',
    file: 'dubai.html',
    type: 'destination',
    icon: '🇦🇪',
    nameDe: 'Dubai',
    title: 'Urlaub in Dubai – Luxus, Strand & Wüste | JetztBuchbar.de',
    description: 'Dubai Urlaub 2026 günstig buchen: Burj Khalifa, JBR Beach, Wüstensafari. Beste Reisezeit, Tipps und Angebote für DACH-Reisende.',
    h1Parts: ['Urlaub in', 'Dubai'],
    heroSub: 'Wolkenkratzer-Skyline, goldene Strände und abenteuerliche Wüstensafaris – Dubai ist das Reiseziel für unvergessliche Erlebnisse.',
    wikiSearch: 'Dubai',
    climateKey: 'dubai',
    countryKey: 'dubai',
    tips: [
      'Kein Visum erforderlich für DACH-Bürger – bei der Einreise gibt es automatisch ein 30-Tage-Visum.',
      'Beste Reisezeit: Oktober bis April mit angenehmen 22–30 °C. Sommer (Juni–August) ist mit bis zu 45 °C extrem heiß.',
      'Kleidungsregeln beachten: In Einkaufszentren, öffentlichen Verkehrsmitteln und Moscheen sind bedeckte Schultern und Knie Pflicht.',
      'Alkohol ist nur in lizenzierten Hotels und Restaurants erhältlich – in der Öffentlichkeit streng verboten.',
      'Die Metro ist das schnellste und günstigste Verkehrsmittel – Nol Card kaufen und Staus vermeiden.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Dubai?', a: 'Nein. DACH-Bürger erhalten bei der Einreise automatisch ein kostenloses 30-Tage-Visum. Eine Verlängerung ist möglich.' },
      { q: 'Wie lange ist der Flug nach Dubai?', a: 'Von Wien oder München dauert ein Direktflug nach Dubai ca. 5,5–6 Stunden. Emirates und Lufthansa bieten tägliche Verbindungen.' },
      { q: 'Welche Währung gilt in Dubai?', a: 'Der Dirham der Vereinigten Arabischen Emirate (AED). 1 Euro entspricht ca. 3,9 AED. Kreditkarten sind überall akzeptiert.' },
      { q: 'Ist Dubai für Familien geeignet?', a: 'Ja, Dubai ist sehr familienfreundlich. Wild Wadi Waterpark, Dubai Frame, Dubai Zoo und unzählige Malls bieten Unterhaltung für alle Altersgruppen.' },
      { q: 'Was kostet ein Urlaub in Dubai?', a: 'Dubai ist teuer, aber es gibt Budgetoptionen. Ein Mittelklasse-Hotel kostet ab 80–120 € pro Nacht. Restaurants variieren stark – von günstigen Food Courts bis zu Luxusrestaurants.' },
    ],
    poiSearch: 'Dubai',
  },
  {
    id: 'kroatien',
    file: 'kroatien.html',
    type: 'destination',
    icon: '🇭🇷',
    nameDe: 'Kroatien',
    title: 'Urlaub in Kroatien – Dubrovnik, Split & Inseln | JetztBuchbar.de',
    description: 'Kroatien Urlaub 2026 günstig buchen: Dubrovnik, Split, Hvar, Nationalparks. Beste Reisezeit, Tipps und Angebote.',
    h1Parts: ['Urlaub in', 'Kroatien'],
    heroSub: 'Kristallklares Adriawasser, mittelalterliche Altstädte und unberührte Nationalparks – Kroatien ist Europas Geheimtipp.',
    wikiSearch: 'Kroatien',
    climateKey: 'kroatien',
    countryKey: 'kroatien',
    tips: [
      'Als EU-Bürger (Deutschland, Österreich) reisen Sie visumfrei ein. Schweizer benötigen nur den Reisepass.',
      'Kroatien verwendet seit 2023 den Euro (€) – kein Geldwechsel mehr nötig.',
      'Beste Reisezeit für Badeurlaub: Juni bis September. Mai und Oktober ideal für Städtereisen ohne Massen.',
      'Frühzeitig buchen: Dubrovnik und Hvar sind im Sommer extrem beliebt – Ferienunterkünfte früh reservieren.',
      'Mit der Fähre lassen sich die kroatischen Inseln (Hvar, Brač, Korčula) einfach und günstig erreichen.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Kroatien?', a: 'Nein. Kroatien ist seit 2023 EU-Mitglied und Teil des Schengenraums. EU-Bürger reisen mit Personalausweis visumfrei ein.' },
      { q: 'Wie lange dauert der Flug nach Kroatien?', a: 'Von Wien nach Dubrovnik oder Split dauert ein Direktflug ca. 1–1,5 Stunden. In der Saison gibt es günstige Direktverbindungen.' },
      { q: 'Welche Währung gilt in Kroatien?', a: 'Kroatien hat seit Januar 2023 den Euro (€) eingeführt. Kein Geldwechsel notwendig für DACH-Reisende.' },
      { q: 'Was kostet Urlaub in Kroatien?', a: 'Kroatien ist günstiger als Westeuropa, aber teurer als Türkei oder Ägypten. Apartments und Ferienhäuser sind besonders beliebt und preiswert.' },
      { q: 'Welche Nationalparks lohnen sich in Kroatien?', a: 'Die Plitvicer Seen (UNESCO-Welterbe), der Nationalpark Krka mit Wasserfällen und der Kornati-Archipel sind absolute Highlights.' },
    ],
    poiSearch: 'Dubrovnik',
  },
  {
    id: 'portugal',
    file: 'portugal.html',
    type: 'destination',
    icon: '🇵🇹',
    nameDe: 'Portugal',
    title: 'Urlaub in Portugal – Lissabon, Algarve & mehr | JetztBuchbar.de',
    description: 'Portugal Urlaub 2026 günstig buchen: Lissabon, Algarve, Porto. Beste Reisezeit, Tipps und Angebote für DACH-Reisende.',
    h1Parts: ['Urlaub in', 'Portugal'],
    heroSub: 'Goldene Steilküsten, Fado-Musik, Pastéis de Nata und das mildeste Klima Westeuropas – Portugal begeistert alle Sinne.',
    wikiSearch: 'Portugal',
    climateKey: 'portugal',
    countryKey: 'portugal',
    tips: [
      'Als EU-Bürger reisen Sie visumfrei nach Portugal. Ein gültiger Personalausweis genügt.',
      'Die Algarve-Küste im Süden hat die schönsten Strände – beste Zeit April bis Oktober.',
      'Lissabon ist ganzjährig eine Reise wert – mild, kulturreich und günstiger als andere Hauptstädte.',
      'Pastéis de Belém in Lissabon probieren – die Original-Pastel de Nata Bäckerei aus dem Jahr 1837.',
      'Mietwagen empfohlen: Portugals schönste Ecken (Alentejo, Douro-Tal) sind mit dem Auto am besten erreichbar.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Portugal?', a: 'Nein. Portugal ist EU-Mitglied. DACH-Bürger reisen mit Personalausweis visumfrei ein.' },
      { q: 'Wann ist die beste Reisezeit für Portugal?', a: 'Mai bis Oktober ist ideal für Badeurlaub. Lissabon und Porto lohnen sich das ganze Jahr – mild, auch im Winter.' },
      { q: 'Wie lange ist der Flug nach Portugal?', a: 'Von Wien oder München dauert ein Direktflug nach Lissabon oder Faro ca. 3–3,5 Stunden.' },
      { q: 'Was ist die beliebteste Region in Portugal?', a: 'Die Algarve im Süden für Strand und Sonne, Lissabon für Stadtkultur, und der Norden (Porto, Douro-Tal) für Wein und Natur.' },
      { q: 'Welche Währung gilt in Portugal?', a: 'Euro (€) – kein Geldwechsel nötig.' },
    ],
    poiSearch: 'Lissabon',
  },
  {
    id: 'bulgarien',
    file: 'bulgarien.html',
    type: 'destination',
    icon: '🇧🇬',
    nameDe: 'Bulgarien',
    title: 'Urlaub in Bulgarien – Sonnenstrand, Goldstrand & Sofia | JetztBuchbar.de',
    description: 'Bulgarien Urlaub 2026 günstig buchen: Sonnenstrand, Goldstrand, Sofia, Varna. Günstigste Schwarzmeerküste Europas.',
    h1Parts: ['Urlaub in', 'Bulgarien'],
    heroSub: 'Europas günstigstes Badeziel: Sonnenstrand, Goldstrand und eine faszinierende Hauptstadt – Bulgarien bietet Qualität zum kleinen Preis.',
    wikiSearch: 'Bulgarien',
    climateKey: 'bulgarien',
    countryKey: 'bulgarien',
    tips: [
      'Als EU-Bürger reisen Sie visumfrei ein – Personalausweis genügt.',
      'Bulgarien ist eines der günstigsten EU-Reiseziele: Hotel, Essen und Aktivitäten kosten deutlich weniger als in Westeuropa.',
      'Die Schwarzmeerküste (Sonnenstrand, Goldstrand) ist ideal für Familien und Budgeturlauber.',
      'Sofia lohnt sich als Städtereise: Alexander-Newski-Kathedrale, Boyana-Kirche (UNESCO) und lebendige Café-Szene.',
      'Bulgarien verwendet noch den Lev (BGN) – Wechselkurs ca. 2 BGN = 1 €.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Bulgarien?', a: 'Nein. Bulgarien ist EU-Mitglied. DACH-Bürger reisen mit Personalausweis visumfrei ein.' },
      { q: 'Ist Bulgarien günstig für Urlaub?', a: 'Ja, Bulgarien gehört zu den günstigsten EU-Reisezielen. All-Inclusive am Sonnenstrand kostet oft ein Drittel von vergleichbaren Angeboten in Spanien.' },
      { q: 'Wie lange dauert der Flug nach Bulgarien?', a: 'Von Wien nach Sofia oder Varna dauert ein Direktflug ca. 1,5–2 Stunden.' },
      { q: 'Welche Währung gilt in Bulgarien?', a: 'Der Bulgarische Lev (BGN) – noch nicht der Euro. Wechselkurs ca. 1,96 BGN pro Euro.' },
      { q: 'Was lohnt sich in Bulgarien neben dem Strand?', a: 'Das Rila-Kloster (UNESCO-Welterbe), das Bachkovo-Kloster, Plovdiv mit der Altstadt und der Nationalpark Pirin sind absolute Empfehlungen.' },
    ],
    poiSearch: 'Sonnenstrand',
  },
  {
    id: 'malta',
    file: 'malta.html',
    type: 'destination',
    icon: '🇲🇹',
    nameDe: 'Malta',
    title: 'Urlaub in Malta – Valletta, Gozo & Strand | JetztBuchbar.de',
    description: 'Malta Urlaub 2026 günstig buchen: Valletta, Gozo, Comino Blue Lagoon. Geschichte, Sonne und kristallklares Mittelmeer.',
    h1Parts: ['Urlaub in', 'Malta'],
    heroSub: 'Der kleinste EU-Staat mit gigantischer Geschichte: Tempelanlagen, Ritterburgen und die berühmte Blue Lagoon erwarten Sie.',
    wikiSearch: 'Malta',
    climateKey: 'malta',
    countryKey: 'malta',
    tips: [
      'Kein Visum nötig als EU-Bürger. Malta ist EU-Mitglied und Schengenland.',
      'Beste Reisezeit: Mai bis Oktober mit 25–35 °C und wenig Regen.',
      'Die Blue Lagoon auf Comino per Fähre besuchen – früh morgens fahren, um Menschenmassen zu vermeiden.',
      'Valletta ist Europas kleinste Hauptstadt und UNESCO-Welterbe – unbedingt die Johanneskathedrale besichtigen.',
      'Englisch ist Amtssprache neben Maltesisch – Verständigung überall problemlos möglich.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Malta?', a: 'Nein. Malta ist EU-Mitglied und Schengenstaat. DACH-Bürger reisen visumfrei ein.' },
      { q: 'Wie lange dauert der Flug nach Malta?', a: 'Von Wien oder München dauert ein Direktflug nach Malta ca. 2,5–3 Stunden.' },
      { q: 'Was ist die Blue Lagoon?', a: 'Die Blue Lagoon auf der kleinen Insel Comino ist eines der schönsten Gewässer Europas – kristallklares, türkisblaues Wasser, ideal zum Schnorcheln und Schwimmen.' },
      { q: 'Welche Währung gilt in Malta?', a: 'Euro (€) – kein Geldwechsel notwendig.' },
      { q: 'Lohnt sich Malta auch für Taucher?', a: 'Ja, Malta ist eines der Top-Tauchreiseziele Europas. Unterwasserhöhlen, Wracks und kristallklares Wasser machen Malta für Taucher sehr attraktiv.' },
    ],
    poiSearch: 'Valletta',
  },
  {
    id: 'zypern',
    file: 'zypern.html',
    type: 'destination',
    icon: '🇨🇾',
    nameDe: 'Zypern',
    title: 'Urlaub in Zypern – Paphos, Ayia Napa & Limassol | JetztBuchbar.de',
    description: 'Zypern Urlaub 2026 günstig buchen: Paphos, Ayia Napa, Limassol, Protaras. Sonne, Strand und antike Geschichte.',
    h1Parts: ['Urlaub in', 'Zypern'],
    heroSub: 'Die Insel der Aphrodite: 340 Sonnentage, antike Stätten und lebhafte Küstenorte machen Zypern zu einem ganzjährigen Reiseziel.',
    wikiSearch: 'Zypern',
    climateKey: 'zypern',
    countryKey: 'zypern',
    tips: [
      'Als EU-Bürger reisen Sie visumfrei nach Zypern ein.',
      'Zypern hat 340 Sonnentage im Jahr – auch Oktober bis April ist sehr angenehm.',
      'Rechtsverkehr gilt in Zypern – das ist ungewöhnlich für ein EU-Land (britisches Erbe).',
      'Paphos ist UNESCO-Welterbe: antike Mosaiken, Aphrodite-Felsen und mittelalterliche Burg gehören zum Pflichtprogramm.',
      'Ayia Napa im Osten für Partytourismus und schöne Strände, Limassol für gehobene Gastronomie und Hafen.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Zypern?', a: 'Nein. Zypern ist EU-Mitglied. DACH-Bürger reisen visumfrei ein.' },
      { q: 'Wann ist die beste Reisezeit für Zypern?', a: 'April bis Oktober für Badeurlaub. Zypern ist auch im Winter mild (15–20 °C) – ideal für Wandern und Kulturreisen.' },
      { q: 'Wie lange dauert der Flug nach Zypern?', a: 'Von Wien oder München beträgt die Flugzeit nach Larnaca ca. 3,5–4 Stunden.' },
      { q: 'Welche Währung gilt in Zypern?', a: 'Euro (€) – kein Geldwechsel notwendig.' },
      { q: 'Was ist der Unterschied zwischen Nord- und Südzypern?', a: 'Der Süden (Republik Zypern) ist EU-Mitglied. Der Norden wird von der Türkei kontrolliert und ist nur eingeschränkt bereisbar. Touristen reisen meist in den Süden.' },
    ],
    poiSearch: 'Paphos',
  },
  {
    id: 'kap-verde',
    file: 'kap-verde.html',
    type: 'destination',
    icon: '🇨🇻',
    nameDe: 'Kap Verde',
    title: 'Urlaub in Kap Verde – Sal, Boa Vista & Santiago | JetztBuchbar.de',
    description: 'Kap Verde Urlaub 2026 buchen: Insel Sal, Boa Vista, Santiago. Ganzjährig Sonne, Surfen und Karibik-Feeling vor Afrika.',
    h1Parts: ['Urlaub in', 'Kap Verde'],
    heroSub: 'Ganzjährig 25 °C, türkisblaues Atlantikmeer und Karibik-Feeling nur 6 Stunden von Europa entfernt – das ist Kap Verde.',
    wikiSearch: 'Kap Verde',
    climateKey: 'kap verde',
    countryKey: 'kap verde',
    tips: [
      'Für DACH-Bürger kein Visum erforderlich – bei der Einreise wird ein Ankunftsvisum ausgestellt (kostenfrei oder geringe Gebühr).',
      'Kap Verde ist ganzjährig bereisbar mit konstant 24–28 °C – kein Sommer-/Winterunterschied.',
      'Sal und Boa Vista sind die Inselkandidaten für Strandurlauber; Santiago für Kultur und Stadtleben.',
      'Der Passat macht Kap Verde zu einem Surfer-Paradies – Windsurf und Kitesurf weltweit bekannt.',
      'Beachte: Infrastruktur auf kleineren Inseln ist einfacher – Luxus-Erwartungen eher auf Sal und Boa Vista erfüllbar.',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Kap Verde?', a: 'Nein, für DACH-Bürger ist kein Visum im Voraus nötig. Bei der Einreise wird ein Ankunftsvisum (EASE) ausgestellt.' },
      { q: 'Wie lange dauert der Flug nach Kap Verde?', a: 'Von Wien oder München beträgt die Flugzeit nach Sal oder Boa Vista ca. 5,5–6 Stunden.' },
      { q: 'Wann ist die beste Reisezeit für Kap Verde?', a: 'Das ganze Jahr über! Temperaturen bleiben konstant bei 24–28 °C. November bis Juni ist die trockenere Saison – ideal für Strandurlaub.' },
      { q: 'Welche Währung gilt auf Kap Verde?', a: 'Der Cabo Verde Escudo (CVE) – an den Euro gebunden. Wechselkurs ca. 110 CVE pro Euro.' },
      { q: 'Ist Kap Verde für Familien geeignet?', a: 'Ja, besonders die Insel Sal mit ruhigem Wasser und flachen Stränden ist sehr familienfreundlich.' },
    ],
    poiSearch: 'Praia',
  },
  {
    id: 'jordanien',
    file: 'jordanien.html',
    type: 'destination',
    icon: '🇯🇴',
    nameDe: 'Jordanien',
    title: 'Urlaub in Jordanien – Petra, Wadi Rum & Totes Meer | JetztBuchbar.de',
    description: 'Jordanien Urlaub 2026 buchen: Petra, Wadi Rum, Totes Meer, Aqaba. Antike Wunder, Wüstenlandschaften und Bademöglichkeiten.',
    h1Parts: ['Urlaub in', 'Jordanien'],
    heroSub: 'Das rosarote Felsenstadt Petra, die Wüste Wadi Rum und das Tote Meer – Jordanien vereint antike Wunder und Naturspektakel.',
    wikiSearch: 'Jordanien',
    climateKey: 'jordanien',
    countryKey: 'jordanien',
    tips: [
      'DACH-Bürger können ein Visum bei der Ankunft (Visa on Arrival) kaufen – ca. 40 USD. Alternativ online beantragen.',
      'Jordan Pass kaufen: Das Kombiticket enthält Visum + Eintritt zu Petra und 40 weiteren Sehenswürdigkeiten.',
      'Beste Reisezeit: März bis Mai und September bis November mit angenehmen 20–28 °C.',
      'Beachte die konservative Kultur: Schultern und Knie bedecken, besonders in Amman und Moscheen.',
      'Das Tote Meer liegt 430 m unter dem Meeresspiegel – das salzigste natürliche Gewässer der Welt. Nicht zu verpassen!',
    ],
    faqs: [
      { q: 'Brauche ich ein Visum für Jordanien?', a: 'Ja, aber DACH-Bürger können es bequem bei der Ankunft (Visa on Arrival, ca. 40 USD) oder online kaufen. Der Jordan Pass enthält das Visum bereits.' },
      { q: 'Wie lange dauert der Flug nach Jordanien?', a: 'Von Wien oder München beträgt die Flugzeit nach Amman ca. 4–4,5 Stunden Direktflug.' },
      { q: 'Was kostet der Eintritt nach Petra?', a: 'Ein Tagesticket kostet ca. 50 JOD (ca. 65 €). Der Jordan Pass ist günstiger, wenn man mehrere Sehenswürdigkeiten besucht.' },
      { q: 'Welche Währung gilt in Jordanien?', a: 'Der Jordanische Dinar (JOD) – eine der stabilsten Währungen der Region. Ca. 0,77 JOD pro Euro (JOD ist stärker als der Euro).' },
      { q: 'Ist Jordanien sicher für Touristen?', a: 'Jordanien gilt als eines der stabilsten und sichersten Länder im Nahen Osten und empfängt jährlich Millionen Touristen.' },
    ],
    poiSearch: 'Petra Jordanien',
  },
];

// ── City pages ────────────────────────────────────────────────────────────────

const CITY_PAGES = [
  // Türkei
  { id: 'antalya', file: 'antalya.html', parent: 'Türkei', parentFile: 'tuerkei.html', icon: '🌊', nameDe: 'Antalya', title: 'Urlaub in Antalya – Die türkische Riviera | JetztBuchbar.de', description: 'Antalya Urlaub 2026: Strände, All-Inclusive-Resorts und die historische Altstadt Kaleiçi. Beste Angebote für DACH-Reisende.', h1Parts: ['Urlaub in', 'Antalya'], heroSub: 'Türkisblaues Meer, goldene Strände und eine 2000 Jahre alte Altstadt – Antalya ist das Herz der türkischen Riviera.', wikiSearch: 'Antalya', climateKey: 'antalya', tips: ['All-Inclusive-Resorts in Belek und Lara bieten top Qualität zum günstigen Preis.', 'Die Altstadt Kaleiçi mit dem Hadrianstor ist ein Muss – besonders abends sehr atmosphärisch.', 'Antalya-Flughafen ist einer der meistfrequentierten der Türkei – viele Direktflüge aus DACH.', 'Düden-Wasserfall und Köprülü-Canyon für Naturliebhaber und Aktivurlauber empfohlen.', 'Viele Resorts bieten kostenlose Kinderbetreuung – ideal für Familien.'], faqs: [{ q: 'Wann ist die beste Reisezeit für Antalya?', a: 'April bis Oktober. Hochsaison Juli/August mit bis zu 40 °C. Mai/Juni und September/Oktober angenehmer.' }, { q: 'Wie weit ist das Stadtzentrum vom Strand?', a: 'Je nach Hotel 5–30 Minuten. Die Resorts in Lara, Belek und Kemer liegen direkt am Meer.' }, { q: 'Gibt es Direktflüge von Wien nach Antalya?', a: 'Ja, Austrian Airlines, TUI und Charterfluggesellschaften fliegen in der Saison direkt nach Antalya (ca. 2,5 Stunden).' }, { q: 'Ist Antalya familienfreundlich?', a: 'Sehr. Riesige Resorts mit Wasserparks, Kinderbetreuung und Aquaparks machen Antalya zu einem Top-Familienziel.' }, { q: 'Was kostet All-Inclusive in Antalya?', a: 'Pro Person ab ca. 400–600 € für 7 Nächte All-Inclusive, je nach Hotel und Saison.' }], poiSearch: 'Antalya' },
  { id: 'bodrum', file: 'bodrum.html', parent: 'Türkei', parentFile: 'tuerkei.html', icon: '⛵', nameDe: 'Bodrum', title: 'Urlaub in Bodrum – Ägäis, Yachten & Nachtleben | JetztBuchbar.de', description: 'Bodrum Urlaub 2026: weiße Häuser, Buchten, Nachtleben und Yacht-Chartern an der Türkischen Ägäis.', h1Parts: ['Urlaub in', 'Bodrum'], heroSub: 'Weiß getünchte Häuser, smaragdgrüne Buchten und eine lebhafte Partyszene – Bodrum ist das St. Tropez der Türkei.', wikiSearch: 'Bodrum', climateKey: 'bodrum', tips: ['Bodrum Castle (Schloss St. Peter) und das Unterwasserarchäologiemuseum nicht verpassen.', 'Bootstrip zu den Buchten (Akyarlar, Karaincir) unbedingt machen – am schönsten per Gulet-Boot.', 'Bodrum Bazaar für lokale Einkäufe: Gewürze, Keramik, Lederwaren.', 'Das Nachtleben in Bodrum ist legendär – Halikarnas Open Air Club ist weltbekannt.', 'Für Ruhesuchende: Güvercinlik und Torba sind ruhigere Alternativen zum pulsierenden Zentrum.'], faqs: [{ q: 'Wann ist die beste Reisezeit für Bodrum?', a: 'Juni bis September. Bodrum ist bekannt für seinen Wind (Meltemi) – ideal zum Segeln, aber gelegentlich unangenehm am Strand.' }, { q: 'Gibt es Direktflüge nach Bodrum?', a: 'Ja, Bodrum Milas Airport hat in der Saison Direktverbindungen aus Wien, München und Zürich.' }, { q: 'Ist Bodrum teurer als andere Türkei-Ziele?', a: 'Ja, Bodrum ist exklusiver und teurer als Antalya oder Alanya – dafür glamouröser und internationaler.' }, { q: 'Welche Strände sind in Bodrum am besten?', a: 'Bitez für Windsurfer, Camel Beach für Familien, und Gümbet für Partytouristen.' }, { q: 'Kann man von Bodrum nach Griechenland?', a: 'Ja! Mit der Fähre ist Kos und Rhodos von Bodrum aus in 30–60 Minuten erreichbar.' }], poiSearch: 'Bodrum' },
  // Griechenland
  { id: 'kreta-stadt', file: 'kreta-urlaub.html', parent: 'Griechenland', parentFile: 'griechenland.html', icon: '🏔️', nameDe: 'Kreta', title: 'Urlaub auf Kreta – Heraklion, Chania & Strände | JetztBuchbar.de', description: 'Kreta Urlaub 2026: Heraklion, Chania, Samaria-Schlucht, Elafonisi. Griechenlands größte Insel entdecken.', h1Parts: ['Urlaub auf', 'Kreta'], heroSub: "Griechenlands größte Insel bietet alles: minoische Paläste, schneeweiße Strände und eine herausragende Küche.", wikiSearch: 'Kreta', climateKey: 'kreta', tips: ['Die Samaria-Schlucht ist eine der längsten Europas – für die 16 km Wanderung früh starten.', 'Elafonisi im Südwesten: der rosafarbene Strand mit türkisblauem Wasser ist einzigartig in Europa.', 'Knossos – der minoische Palast bei Heraklion – ist Pflicht für Geschichtsinteressierte.', 'Frische Meeresfrüchte in Elounda oder Agios Nikolaos – weit günstiger als auf kleineren Inseln.', 'Mietwagen empfohlen: Kreta ist groß, die schönsten Teile liegen weit auseinander.'], faqs: [{ q: 'Wie komme ich nach Kreta?', a: 'Direktflüge nach Heraklion (HER) oder Chania (CHQ) von Wien oder München in ca. 2,5–3 Stunden.' }, { q: 'Welche Seite Kretas ist schöner – Nord oder Süd?', a: 'Norden für Komfort und Resorts, Süden für wilde Natur und einsame Strände. Am besten beide erleben.' }, { q: 'Ist Kreta für Familien geeignet?', a: 'Sehr. Viele familienfreundliche Resorts, ruhige Buchten und Kinderanimation. Besonders Hersonissos und Malia empfohlen.' }, { q: 'Was kostet Urlaub auf Kreta?', a: 'Günstiger als viele andere griechische Inseln. 7 Nächte Halbpension ab ca. 500–700 € pro Person.' }, { q: 'Wann hat Kreta Hauptsaison?', a: 'Juli und August sind vollbesetzt. Mai, Juni und September sind ideal mit weniger Touristen und niedrigeren Preisen.' }], poiSearch: 'Heraklion Kreta' },
  { id: 'santorini-stadt', file: 'santorini-urlaub.html', parent: 'Griechenland', parentFile: 'griechenland.html', icon: '🌅', nameDe: 'Santorini', title: 'Urlaub auf Santorini – Oia, Sonnenuntergang & Vulkan | JetztBuchbar.de', description: 'Santorini Urlaub 2026: Oia, Fira, Caldera, Vulkantour. Das romantischste Reiseziel Griechenlands.', h1Parts: ['Urlaub auf', 'Santorini'], heroSub: 'Weiß-blaue Kykladen-Architektur, spektakuläre Caldera und der berühmteste Sonnenuntergang der Welt – Santorini verzaubert jeden.', wikiSearch: 'Santorin', climateKey: 'santorini', tips: ['Den Sonnenuntergang von Oia erleben – frühzeitig einen Platz sichern, es wird voll.', 'Mit dem Boot zur Caldera und zum aktiven Vulkan – unvergessliches Erlebnis.', 'Akrotiri: die minoische Ausgrabungsstätte ist das "Pompeji Griechenlands".', 'Santorini-Wein probieren: Assyrtiko-Weißwein wächst auf der vulkanischen Erde und ist weltweit einzigartig.', 'Preise sind hoch – früh buchen und für Restaurants Reservierungen machen.'], faqs: [{ q: 'Wie komme ich nach Santorini?', a: 'Direktflug nach Thira (JTR) ca. 2,5 Stunden ab Wien/München, oder Fähre von Athen (Piräus) in 5–8 Stunden.' }, { q: 'Ist Santorini geeignet für Familien?', a: 'Eher nein – Santorini ist romantisch und auf Paare/Honeymoon ausgerichtet. Wenig Strandoptionen, viele Treppen.' }, { q: 'Wann ist die beste Reisezeit für Santorini?', a: 'Mai bis Oktober. Außerhalb der Hochsaison (Juli/August) sind Preise günstiger und weniger überfüllt.' }, { q: 'Was kostet eine Übernachtung in Oia?', a: 'Oia gehört zu den teuersten Reisezielen Griechenlands – Zimmer ab 150 € pro Nacht in der Hauptsaison, Suiten mit Caldera-Blick bis 1000 €+.' }, { q: 'Warum sind die Häuser in Santorini weiß und blau?', a: 'Weiß reflektiert die Sommerhitze, und Blau war historisch günstigste Farbe. Heute ist es gesetzlich vorgeschrieben für das Erscheinungsbild der Insel.' }], poiSearch: 'Santorini' },
];

// ── Reisezeit pages ───────────────────────────────────────────────────────────

const REISEZEIT_PAGES = [
  { id: 'reisezeit-tuerkei', file: 'beste-reisezeit-tuerkei.html', nameDe: 'Türkei', destFile: 'tuerkei.html', icon: '🇹🇷', title: 'Beste Reisezeit Türkei 2026 – Wann reisen? | JetztBuchbar.de', description: 'Wann ist die beste Reisezeit für die Türkei? Klima, Temperaturen und Tipps für jede Jahreszeit.' },
  { id: 'reisezeit-spanien', file: 'beste-reisezeit-spanien.html', nameDe: 'Spanien', destFile: 'spanien.html', icon: '🇪🇸', title: 'Beste Reisezeit Spanien 2026 – Mallorca, Teneriffa & mehr | JetztBuchbar.de', description: 'Wann ist die beste Reisezeit für Spanien? Klimatabelle, Temperaturen und Tipps nach Region.' },
  { id: 'reisezeit-griechenland', file: 'beste-reisezeit-griechenland.html', nameDe: 'Griechenland', destFile: 'griechenland.html', icon: '🇬🇷', title: 'Beste Reisezeit Griechenland 2026 | JetztBuchbar.de', description: 'Wann ist die beste Reisezeit für Griechenland? Kreta, Santorini und die Inseln im Klimavergleich.' },
  { id: 'reisezeit-aegypten', file: 'beste-reisezeit-aegypten.html', nameDe: 'Ägypten', destFile: 'aegypten.html', icon: '🇪🇬', title: 'Beste Reisezeit Ägypten 2026 – Hurghada & Sharm | JetztBuchbar.de', description: 'Wann ist die beste Reisezeit für Ägypten? Klimavergleich Hurghada, Sharm el-Sheikh und Kairo.' },
  { id: 'reisezeit-marokko', file: 'beste-reisezeit-marokko.html', nameDe: 'Marokko', destFile: 'marokko.html', icon: '🇲🇦', title: 'Beste Reisezeit Marokko 2026 | JetztBuchbar.de', description: 'Wann nach Marokko reisen? Klimatabelle Marrakesch, Agadir und die beste Jahreszeit.' },
  { id: 'reisezeit-dubai', file: 'beste-reisezeit-dubai.html', nameDe: 'Dubai', destFile: 'dubai.html', icon: '🇦🇪', title: 'Beste Reisezeit Dubai 2026 – Oktober bis April ideal | JetztBuchbar.de', description: 'Wann nach Dubai reisen? Klimatable, Temperaturen und Tipps für den perfekten Zeitpunkt.' },
  { id: 'reisezeit-portugal', file: 'beste-reisezeit-portugal.html', nameDe: 'Portugal', destFile: 'portugal.html', icon: '🇵🇹', title: 'Beste Reisezeit Portugal 2026 – Algarve & Lissabon | JetztBuchbar.de', description: 'Wann nach Portugal reisen? Klimavergleich Algarve, Lissabon und Porto nach Monaten.' },
  { id: 'reisezeit-malta', file: 'beste-reisezeit-malta.html', nameDe: 'Malta', destFile: 'malta.html', icon: '🇲🇹', title: 'Beste Reisezeit Malta 2026 | JetztBuchbar.de', description: 'Wann nach Malta reisen? Klimatabelle und Empfehlungen für den besten Urlaubszeitpunkt.' },
];

// ── Thema pages ───────────────────────────────────────────────────────────────

const THEMA_PAGES = [
  {
    id: 'urlaub-mit-kindern',
    file: 'urlaub-mit-kindern.html',
    icon: '👨‍👩‍👧‍👦',
    title: 'Urlaub mit Kindern 2026 – Die besten Familienziele | JetztBuchbar.de',
    description: 'Die besten Familienreiseziele 2026: Türkei, Spanien, Griechenland. Tipps für Urlaub mit Kindern und Top-Resorts.',
    h1Parts: ['Urlaub mit', 'Kindern'],
    heroSub: 'Familienurlaub perfekt geplant: die besten kinderfreundlichen Resorts, Strände und Aktivitäten für unvergessliche Ferien.',
    intro: 'Urlaub mit Kindern erfordert besondere Planung: flache Strände, gute Kinderbetreuung, abwechslungsreiche Aktivitäten und sichere Unterkünfte. Diese Seite hilft Ihnen, das ideale Familienziel zu finden.',
    tips: [
      'All-Inclusive-Resorts mit Kinderclub sind ideal für Familien – Eltern können sich entspannen, Kinder werden betreut.',
      'Flache Sandstrände ohne Wellen bevorzugen: Lara Beach (Antalya), Side oder Mallorca sind ideal für kleine Kinder.',
      'Außerhalb der Hochsaison reisen (Juni oder September) – weniger überfüllt, günstiger, angenehmer für Kinder.',
      'Snacks und Lieblingsspielzeug einpacken – lange Flüge und Wartezeiten werden mit Vorbereitung einfacher.',
      'Kinderreisepass rechtzeitig beantragen – mindestens 6 Wochen vor der Reise beim Standesamt.',
    ],
    faqs: [
      { q: 'Welche Ziele sind am besten für Urlaub mit kleinen Kindern?', a: 'Antalya, Side und Alanya in der Türkei sowie Mallorca bieten flache Strände, große Resorts mit Animation und sind von DACH gut erreichbar.' },
      { q: 'Ab welchem Alter können Kinder in den Flugzeug?', a: 'Babys ab 1 Woche sind flugfähig, aber Ärzte empfehlen zu warten bis das Kind 4–6 Wochen alt ist. Ab 2 Jahren benötigen Kinder einen eigenen Sitzplatz.' },
      { q: 'Welche Impfungen brauchen Kinder für Auslandsreisen?', a: 'Für EU-Reiseziele meist keine Pflichtimpfungen. Für Ägypten, Marokko oder Tunesien Hepatitis A und Typhus empfohlen – Kinderarzt konsultieren.' },
      { q: 'Was ist der Unterschied zwischen Kinderclub und Animation?', a: 'Kinderclub bietet professionelle Betreuung für bestimmte Altersgruppen. Animation ist Unterhaltung für alle Altersgruppen (Shows, Spiele, Sport).' },
      { q: 'Wie viel Gepäck darf ein Kind mitbringen?', a: 'Je nach Airline bekommen Kinder ab 2 Jahren dasselbe Freigepäck wie Erwachsene. Babys unter 2 Jahren haben oft kein oder reduziertes Freigepäck.' },
    ],
    destinations: ['Türkei', 'Spanien', 'Griechenland', 'Bulgarien'],
  },
  {
    id: 'flitterwochen',
    file: 'flitterwochen.html',
    icon: '💑',
    title: 'Flitterwochen & Hochzeitsreisen 2026 – Romantische Ziele | JetztBuchbar.de',
    description: 'Traumhafte Flitterwochen-Ziele 2026: Santorini, Malediven, Dubai, Bali. Tipps und Inspiration für Ihre Hochzeitsreise.',
    h1Parts: ['Flitterwochen &', 'Hochzeitsreisen'],
    heroSub: 'Ihr schönster Urlaub verdient das romantischste Ziel. Entdecken Sie die beliebtesten Flitterwochen-Destinationen 2026.',
    intro: 'Flitterwochen sind die vielleicht wichtigste Reise des Lebens. Von Santorinis Sonnenuntergängen bis zu Dubais Luxushotels – wir helfen Ihnen, die perfekte Honeymoon-Destination zu finden.',
    tips: [
      'Frühzeitig buchen: Die besten Honeymoon-Suiten in Santorini und Dubai sind oft 6–12 Monate im Voraus ausgebucht.',
      'Als Flitterwochen-Paar beim Einchecken mitteilen – viele Hotels bieten kostenlose Upgrades oder Willkommensgeschenke.',
      'Santorini von Mai bis Oktober, Malediven und Dubai Oktober bis April – Reisezeit dem Ziel anpassen.',
      'Privat-Pool-Villa oder Overwater-Bungalow für ultimative Privatsphäre und Romantik.',
      'Dinner bei Sonnenuntergang reservieren – besonders in Oia (Santorini) oder auf dem Burj Khalifa (Dubai).',
    ],
    faqs: [
      { q: 'Welches ist das romantischste Reiseziel für Flitterwochen?', a: 'Santorini gilt weltweit als romantischstes Reiseziel. Dubai für Luxus, Bali für Natur und Spiritualität, Malediven für Overwater-Bungalows.' },
      { q: 'Wie viel sollte man für Flitterwochen budgetieren?', a: 'Von 2.000 € (Santorini/Zypern) bis 10.000 €+ (Malediven/Bali). Das richtige Budget hängt von Destination und Luxuslevel ab.' },
      { q: 'Wann sollte man Flitterwochen buchen?', a: 'Mindestens 6–12 Monate vor der Hochzeit. Hochzeiten finden oft im Sommer statt – Hochsaison-Hotels früh reservieren.' },
      { q: 'Was sollte man in die Flitterwochen-Planung einbeziehen?', a: 'Visumsanforderungen, Reiseversicherung, romantische Aktivitäten (privates Dinner, Bootstouren), besondere Unterkünfte und Überraschungen.' },
      { q: 'Gibt es spezielle Flitterwochen-Pakete bei Hotels?', a: 'Ja, viele Hotels bieten Honeymoon-Pakete: Champagner bei Ankunft, Blumendekoration, Spa-Gutscheine und spezielle Dinner-Reservierungen.' },
    ],
    destinations: ['Santorini', 'Dubai', 'Zypern', 'Portugal'],
  },
  {
    id: 'last-minute',
    file: 'last-minute-urlaub.html',
    icon: '⚡',
    title: 'Last Minute Urlaub 2026 – Günstig spontan reisen | JetztBuchbar.de',
    description: 'Last Minute Urlaub günstig buchen: Türkei, Spanien, Griechenland, Ägypten. Die besten Tipps für spontanes Reisen.',
    h1Parts: ['Last Minute', 'Urlaub'],
    heroSub: 'Spontan verreisen und dabei richtig sparen – mit den richtigen Tipps sind Last-Minute-Angebote oft die günstigsten des Jahres.',
    intro: 'Last-Minute-Urlaub bedeutet nicht schlechtere Qualität – oft ist es das Gegenteil. Hotels und Reiseveranstalter senken kurz vor Abreise die Preise drastisch, um freie Kapazitäten zu füllen.',
    tips: [
      'Beste Last-Minute-Deals gibt es 7–14 Tage vor Abreise – besonders für All-Inclusive in Türkei und Ägypten.',
      'Flexibel bleiben: Wer Ziel und Datum offen lässt, findet die günstigsten Angebote.',
      'Werktags früh morgens nach Angeboten suchen – neue Deals werden oft in den frühen Morgenstunden eingestellt.',
      'Handgepäck-only Angebote sparen nochmals 20–40 € pro Person.',
      'Reiseversicherung auch bei Last-Minute-Buchungen abschließen – besonders für Krankenversicherung im Ausland.',
    ],
    faqs: [
      { q: 'Wie weit im Voraus ist Last-Minute?', a: 'Last-Minute gilt typischerweise für Reisen, die 1–4 Wochen vor Abreise gebucht werden. Die günstigsten Angebote oft 7–10 Tage vor Reisebeginn.' },
      { q: 'Welche Ziele sind für Last-Minute am besten?', a: 'Türkei (Antalya, Alanya), Ägypten (Hurghada), Spanien (Mallorca, Teneriffa) – große Resorts mit vielen Betten haben oft Last-Minute-Verfügbarkeit.' },
      { q: 'Ist Last-Minute wirklich günstiger?', a: 'Ja, oft 30–50 % günstiger als Früh-Buchung. Aber Zimmerauswahl und Lage können eingeschränkt sein.' },
      { q: 'Brauche ich eine Reiseversicherung bei Last-Minute?', a: 'Unbedingt. Besonders Auslandskrankenversicherung und Reiserücktrittsversicherung sind wichtig – auch bei kurzfristiger Buchung.' },
      { q: 'Kann ich Last-Minute auch für Familien buchen?', a: 'Ja, aber Familienzimmer/-suiten sind früher ausgebucht. Bei Familien empfehlen wir daher maximal 2–3 Wochen Vorlaufzeit.' },
    ],
    destinations: ['Türkei', 'Ägypten', 'Spanien', 'Bulgarien'],
  },
  {
    id: 'all-inclusive',
    file: 'all-inclusive-urlaub.html',
    icon: '🍹',
    title: 'All Inclusive Urlaub 2026 – Beste Resorts & Ziele | JetztBuchbar.de',
    description: 'All-Inclusive-Urlaub 2026 günstig buchen: Türkei, Spanien, Ägypten. Die besten All-Inclusive-Resorts für jeden Geldbeutel.',
    h1Parts: ['All Inclusive', 'Urlaub'],
    heroSub: 'Sorglos genießen ohne ständig ans Portemonnaie denken – All-Inclusive-Urlaub ist die entspannteste Art zu reisen.',
    intro: 'All-Inclusive bedeutet: Unterkunft, alle Mahlzeiten, Snacks und Getränke (meist auch Alkohol) sowie viele Aktivitäten im Preis inbegriffen. Besonders für Familien und in der Türkei extrem beliebt.',
    tips: [
      'Antalya und Alanya bieten das beste All-Inclusive-Preis-Leistungs-Verhältnis in Europa – Qualität für kleines Geld.',
      'Ultra All-Inclusive vs. Standard: "Ultra AI" schließt auch Premium-Spirituosen, À-la-carte-Restaurants und Ausflüge ein.',
      'Ressort-Lage prüfen: direkt am Strand oder mit Transfer? Stromanbieter auf der Website des Resorts ansehen.',
      'Animationsprogramm und Kinderclub in der Hotelbeschreibung überprüfen – je nach Reisegruppe wichtig.',
      'Reiseversicherung abschließen: Bei All-Inclusive-Buchungen ist die Gesamtsumme hoch – Stornoschutz lohnt sich.',
    ],
    faqs: [
      { q: 'Was ist im All-Inclusive-Urlaub inklusive?', a: 'Unterkunft, alle Mahlzeiten (Frühstück, Mittagessen, Abendessen), Snacks zwischendurch, lokale Getränke (Alkohol und alkoholfrei). Extras je nach Hotel.' },
      { q: 'Welches Land bietet das beste All-Inclusive?', a: 'Die Türkei (besonders Antalya) gilt als Weltmeister im All-Inclusive-Segment: sehr hohe Qualität zu günstigen Preisen.' },
      { q: 'Was ist Ultra All-Inclusive?', a: 'Ultra AI ist die Premium-Stufe: Premium-Getränke aller Marken, mehrere À-la-carte-Restaurants, Spa-Nutzung und oft auch Ausflüge oder Wassersport inklusive.' },
      { q: 'Lohnt sich All-Inclusive für Paare ohne Kinder?', a: 'Ja, besonders wenn man im Hotel entspannen will. Wer lieber lokale Restaurants entdeckt, spart mit Halbpension und profitiert mehr vom Ort.' },
      { q: 'Wie bucht man günstig All-Inclusive?', a: 'Frühbucher-Rabatte (5–7 Monate vor Abreise) oder Last-Minute (1–2 Wochen). Vergleichsportale und direkte Anfragen beim Reisebüro empfohlen.' },
    ],
    destinations: ['Türkei', 'Ägypten', 'Spanien', 'Bulgarien'],
  },
];

// ── Hotel pages ───────────────────────────────────────────────────────────────

const HOTEL_PAGES = [
  {
    id: 'hotels-antalya',
    file: 'hotels-antalya.html',
    type: 'hotel',
    icon: '🏨',
    nameDe: 'Antalya',
    title: 'Beste Hotels in Antalya 2026 – Top Resorts & Bewertungen | JetztBuchbar.de',
    description: 'Die besten Hotels und Resorts in Antalya 2026: Luxus, All-Inclusive und Familienhotels. Tipps und Empfehlungen für jeden Geldbeutel.',
    h1Parts: ['Beste Hotels in', 'Antalya'],
    heroSub: 'Von Luxusresorts am Lara Beach bis zu familienfreundlichen All-Inclusive-Hotels – hier finden Sie das perfekte Hotel in Antalya.',
    climateKey: 'antalya',
    tips: [
      'Lara Beach und Belek sind die begehrtesten Hotelregionen – Top-Resorts mit direktem Strandzugang.',
      'Frühbucher (6–8 Monate vorher) sparen bis zu 40 % gegenüber Last-Minute-Preisen.',
      'Ultra All-Inclusive lohnt sich besonders für Familien – alle Mahlzeiten, Getränke und Animation inklusive.',
      'Side und Alanya bieten günstigere Alternativen mit ähnlichem Strandangebot.',
      'Bewertungen auf TripAdvisor und HolidayCheck vergleichen – besonders Sauberkeit und Strand-Entfernung prüfen.',
    ],
    faqs: [
      { q: 'Welche Hotelregion in Antalya ist die beste?', a: 'Lara Beach für Luxus, Belek für Golfer und Familien, Alanya für günstigere All-Inclusive-Angebote, Kemer für Natur und Bergkulisse.' },
      { q: 'Wann bucht man Antalya-Hotels am günstigsten?', a: 'Frühbucher 5–8 Monate vor Abreise für beste Auswahl. Last-Minute 1–3 Wochen vorher, wenn Verfügbarkeit vorhanden.' },
      { q: 'Gibt es gute Familienhotels in Antalya?', a: 'Ja, Antalya ist besonders familienfreundlich. Hotels wie Rixos, WOW und Titanic bieten Kinderclubs, Wasserparks und spezielle Kindermenüs.' },
      { q: 'Was kostet ein gutes Hotel in Antalya?', a: 'All-Inclusive für 2 Personen/Woche ab ca. 600–1.200 € im Frühbuchertarif. Luxusresorts (5-Sterne) ab 1.500 € pro Woche pro Person.' },
      { q: 'Ist WLAN in Antalya-Hotels inklusive?', a: 'Bei den meisten 4- und 5-Sterne-Hotels ja. In günstigeren Unterkünften ist WLAN oft auf die Lobby beschränkt.' },
    ],
  },
  {
    id: 'hotels-dubai',
    file: 'hotels-dubai.html',
    type: 'hotel',
    icon: '🏙️',
    nameDe: 'Dubai',
    title: 'Beste Hotels in Dubai 2026 – Luxus & Strandhotels | JetztBuchbar.de',
    description: 'Top Hotels in Dubai 2026: Burj Al Arab, Palm-Jumeirah-Resorts, JBR-Beach-Hotels. Alle Lagen, alle Preisklassen erklärt.',
    h1Parts: ['Beste Hotels in', 'Dubai'],
    heroSub: 'Ikonen wie der Burj Al Arab, Strandresorts auf der Palm Jumeirah und urbane Boutique-Hotels – Dubai bietet die spektakulärsten Übernachtungen weltweit.',
    climateKey: 'dubai',
    tips: [
      'Palm Jumeirah für Strandurlaub und Luxus, Downtown Dubai für Sightseeing und Bequemlichkeit.',
      'Jumeirah Beach Residence (JBR) ist ideal für Reisende, die Strand + Shopping + Restaurants kombinieren wollen.',
      'Buchung über offizielle Hotel-Websites oft günstiger als Portale – Loyalty-Programme nutzen.',
      'Preise im Ramadan deutlich günstiger – Restaurants tagsüber geschlossen, aber Hotels bieten Service.',
      'Strandhotels haben eigenen Strand – wichtig bei Buchen, da öffentliche Strände begrenzt sind.',
    ],
    faqs: [
      { q: 'Welches ist das beste Hotel in Dubai?', a: 'Burj Al Arab (ultra-luxus), Atlantis The Palm (Familien & Wasserpark), Address Downtown (Sightseeing). Beste Wahl hängt vom Reisezweck ab.' },
      { q: 'Wie teuer sind Hotels in Dubai?', a: '4-Sterne ab 80–150 €/Nacht. 5-Sterne ab 200–500 €/Nacht. Ikonische Hotels wie Burj Al Arab ab 1.500 €/Nacht.' },
      { q: 'Welche Hotelinsel ist besser – Palm oder JBR?', a: 'Palm Jumeirah für gehobene Ruhe und exklusive Resorts. JBR für lebhaftere Atmosphäre mit Walk, Restaurants und Strandzugang.' },
      { q: 'Gibt es günstige Hotels in Dubai?', a: 'Ja, Bur Dubai und Deira bieten Budget-Hotels ab 40–60 €/Nacht. Metro-Anbindung ermöglicht Ausflüge ins Zentrum.' },
      { q: 'Wann sind Dubai-Hotels am günstigsten?', a: 'Juni bis August (Sommer) deutlich günstiger, aber extreme Hitze. Beste Preise für angenehmes Wetter im Oktober und April.' },
    ],
  },
  {
    id: 'hotels-kreta',
    file: 'hotels-kreta.html',
    type: 'hotel',
    icon: '🏖️',
    nameDe: 'Kreta',
    title: 'Beste Hotels auf Kreta 2026 – Resorts & Boutique-Hotels | JetztBuchbar.de',
    description: 'Top Hotels auf Kreta 2026: Heraklion, Chania, Elounda. Luxus-Resorts, Familienhotels und authentische Unterkünfte.',
    h1Parts: ['Beste Hotels auf', 'Kreta'],
    heroSub: 'Zwischen Palmenstrände und Weißgebirge: Kretas Hotels reichen von Palazzo-Luxus in Elounda bis zu familiären Pensionen in Chania.',
    climateKey: 'kreta',
    tips: [
      'Elounda und Agios Nikolaos für Luxus und Ruhe – hier befinden sich einige der besten Resorts Griechenlands.',
      'Chania-Altstadt für romantische Boutique-Hotels in venezianischen Gebäuden – perfekt für Paare.',
      'Malia und Hersonissos für Partytourismus und günstigere Unterkünfte.',
      'Westküste (Kissamos, Chania) ruhiger und authentischer, Ostküste (Sitia) für Offbeat-Reisende.',
      'Kreta-Urlaub wird meist all-inclusive gebucht – Vergleich mit Übernachtung+Frühstück lohnt sich.',
    ],
    faqs: [
      { q: 'Welche Region auf Kreta für welchen Urlaubstyp?', a: 'Elounda/Agios Nikolaos für Luxus, Chania für Kultur & Romantik, Heraklion für Sightseeing, Malia/Hersonissos für Partytourismus.' },
      { q: 'Wann sind Kreta-Hotels am günstigsten?', a: 'Mai, Juni und September/Oktober bieten bestes Preis-Leistungs-Verhältnis – gutes Wetter, weniger Massen, günstigere Preise als Juli/August.' },
      { q: 'Gibt es gute Familienhotels auf Kreta?', a: 'Ja, viele Resorts im Raum Heraklion und Rethymno haben umfangreiche Kinderclubs und familienfreundliche Ausstattung.' },
      { q: 'Was kostet Urlaub auf Kreta im Hotel?', a: 'Ab ca. 500–800 € pro Person/Woche all-inclusive im Sommer. Boutique-Hotels ab 60–100 €/Nacht.' },
      { q: 'Gibt es Adults-Only-Hotels auf Kreta?', a: 'Ja, besonders in Elounda und Hersonissos gibt es mehrere exklusive Adults-Only-Resorts für Paare und Genießer.' },
    ],
  },
  {
    id: 'hotels-mallorca',
    file: 'hotels-mallorca.html',
    type: 'hotel',
    icon: '⛵',
    nameDe: 'Mallorca',
    title: 'Beste Hotels auf Mallorca 2026 – Resorts & Fincas | JetztBuchbar.de',
    description: 'Top Hotels auf Mallorca 2026: Palma, Alcúdia, Port de Sóller. Luxusresorts, Finca-Hotels und günstige Strandhotels.',
    h1Parts: ['Beste Hotels auf', 'Mallorca'],
    heroSub: 'Von Finca-Hotels in der Serra de Tramuntana bis zu Beachclubs in Cala Millor – Mallorca hat für jeden Geschmack die richtige Unterkunft.',
    climateKey: 'mallorca',
    tips: [
      'Palma für Stadtflair und Kulinarik, Alcúdia für Familien am Nordstrand, Port de Sóller für Bergromantik.',
      'Finca-Hotels bieten das authentischste Mallorca-Erlebnis – Olivenhaine, Pools und ruhige Lage.',
      'Finca mieten vs. Hotel: Bei Gruppen ab 4 Personen oft günstiger und persönlicher.',
      'Cala d\'Or und Santanyí im Südosten für ruhigere, weniger überlaufene Strände.',
      'Frühbuchung unbedingt – Mallorca ist im Sommer extrem beliebt, gute Hotels früh ausgebucht.',
    ],
    faqs: [
      { q: 'Welche Region auf Mallorca ist am schönsten?', a: 'Das kommt auf den Typ an: Palma für Kultur, Tramuntana für Natur & Wandern, Alcúdia für Familien-Strand, Ses Salines für Luxus.' },
      { q: 'Was sind Finca-Hotels auf Mallorca?', a: 'Umgebaute mallorquinische Bauernhöfe (Fincas) mit eigenem Pool, Garten und persönlichem Service – das Beste von Landhaus und Hotel.' },
      { q: 'Wie teuer ist Mallorca im Vergleich zu anderen Zielen?', a: 'Mallorca liegt im oberen Mittelfeld. Günstiger als Ibiza oder Formentera, teurer als Türkei oder Bulgarien.' },
      { q: 'Wann ist die beste Zeit für Mallorca-Urlaub?', a: 'Mai, Juni und September – bestes Wetter (25–28 °C), weniger Touristen als Juli/August, faire Preise.' },
      { q: 'Gibt es gute Hotels für Senioren auf Mallorca?', a: 'Ja, viele Hotels in Alcúdia und Cala Ratjada sind barrierefrei und seniorenfreundlich mit Aufzügen, flachem Strand und medizinischer Nähe.' },
    ],
  },
  {
    id: 'hotels-lissabon',
    file: 'hotels-lissabon.html',
    type: 'hotel',
    icon: '🏛️',
    nameDe: 'Lissabon',
    title: 'Beste Hotels in Lissabon 2026 – Boutique & Luxus | JetztBuchbar.de',
    description: 'Top Hotels in Lissabon 2026: Alfama, Chiado, Bairro Alto. Boutique-Hotels, Design-Hotels und günstige Unterkünfte.',
    h1Parts: ['Beste Hotels in', 'Lissabon'],
    heroSub: 'Historische Palast-Hotels in der Alfama, coole Design-Boutiques im Chiado und Panorama-Rooftops über den roten Dächern – Lissabon übernachtet einmalig.',
    climateKey: 'lissabon',
    tips: [
      'Chiado und Bairro Alto sind die besten Lagen für zentrale Hotels – zu Fuß zu allen Highlights.',
      'Alfama-Hotels für Fado-Atmosphäre und Aussicht auf den Tejo – aber Gehentfernung zu Aufzügen prüfen.',
      'Boutique-Hotels in umgebauten Azulejo-Palästen bieten das authentischste Lissabon-Erlebnis.',
      'Oriente-Viertel (Parque das Nações) für moderne Hotels mit guter Metro-Anbindung und günstigere Preise.',
      'Ganzjährig reisbar – auch im Winter angenehm mild (14–17 °C) und günstigere Hotelpreise.',
    ],
    faqs: [
      { q: 'Welches Viertel in Lissabon für Hotels?', a: 'Chiado/Bairro Alto für Lage & Atmosphere, Alfama für Altstadt-Charme, Baixa/Rossio für günstigere Hotels mit zentraler Lage.' },
      { q: 'Was sind typische Hotelpreise in Lissabon?', a: 'Budget-Hotels ab 40–70 €/Nacht. Boutique-Hotels 100–200 €/Nacht. Luxushotels ab 250–500 €/Nacht.' },
      { q: 'Gibt es günstige Unterkünfte in Lissabon?', a: 'Ja, Hostels und Budget-Guesthouses im Martinhal-Viertel und Mouraria ab 20–40 €/Nacht. Sehr beliebt bei Backpackern.' },
      { q: 'Haben Lissabon-Hotels Parkplätze?', a: 'Selten im Stadtzentrum – kostenpflichtiges Parken oder Park-and-Ride empfohlen. Metro und Tram sind besser für die Innenstadt.' },
      { q: 'Wann sind Hotels in Lissabon am günstigsten?', a: 'November bis Februar (außer Silvester) deutlich günstiger. Lissabon hat ganzjährig mildes Klima – auch Winter ist angenehm.' },
    ],
  },
];

// ── Aktivität pages ────────────────────────────────────────────────────────────

const AKTIVITAET_PAGES = [
  {
    id: 'schnorcheln-kreta',
    file: 'schnorcheln-kreta.html',
    type: 'aktivitaet',
    icon: '🤿',
    nameDe: 'Kreta',
    aktivitaet: 'Schnorcheln',
    title: 'Schnorcheln auf Kreta 2026 – Beste Spots & Tipps | JetztBuchbar.de',
    description: 'Die besten Schnorchelspots auf Kreta: Elafonisi, Balos, Bali und mehr. Tipps für Anfänger und Fortgeschrittene.',
    h1Parts: ['Schnorcheln auf', 'Kreta'],
    heroSub: 'Kristallklares Mittelmeer, bunte Fische und versteckte Buchten – Kreta ist eines der besten Schnorchelziele Europas.',
    climateKey: 'kreta',
    tips: [
      'Elafonisi und Balos sind Traumstrände mit klarem Wasser, aber oft überfüllt – früh morgens hinfahren.',
      'Die Ostküste (Sitia, Kouremenos) bietet ruhigere und weniger bekannte Schnorchelspots.',
      'Ausrüstung vor Ort leihen ist möglich – eigene Maske mitbringen empfohlen für bessere Passform.',
      'Bestes Schnorcheln von Mai bis Oktober mit Wassertemperaturen von 20–26 °C.',
      'Meeresschutzgebiete respektieren – nichts berühren oder mitnehmen, Korallenriffe schützen.',
    ],
    faqs: [
      { q: 'Wo schnorchelt man am besten auf Kreta?', a: 'Elafonisi für pinken Sand und klares Wasser, Bali für kleine Buchten, Kissamos für tiefere Gewässer, Agios Nikolaos für Unterwasserhöhlen.' },
      { q: 'Kann man auf Kreta auch tauchen?', a: 'Ja, Kreta hat mehrere Tauchzentren. Besonders bekannt: Agios Nikolaos, Heraklion und Rethymno für geführte Tauchangänge.' },
      { q: 'Wie warm ist das Wasser auf Kreta?', a: 'Im Sommer (Juli–August) 25–27 °C. Im Mai bereits 20–22 °C – angenehm zum Schnorcheln. Oktober noch ca. 23 °C.' },
      { q: 'Brauche ich einen Tauchschein zum Schnorcheln?', a: 'Nein, Schnorcheln erfordert keinen Schein. Für Gerätetauchen wird ein Tauchschein (PADI/SSI) benötigt.' },
      { q: 'Gibt es Schnorcheltouren auf Kreta?', a: 'Ja, geführte Bootstouren zu den besten Spots werden in allen Urlaubsorten angeboten, ab ca. 25–50 € pro Person.' },
    ],
  },
  {
    id: 'tauchen-malta',
    file: 'tauchen-malta.html',
    type: 'aktivitaet',
    icon: '🐠',
    nameDe: 'Malta',
    aktivitaet: 'Tauchen',
    title: 'Tauchen in Malta 2026 – Wracks, Höhlen & Top-Spots | JetztBuchbar.de',
    description: 'Malta ist Europas Top-Tauchreiseziel: Unterwasserhöhlen, Wracks und kristallklares Mittelmeer. Beste Spots, Saison und Tauchschulen.',
    h1Parts: ['Tauchen in', 'Malta'],
    heroSub: 'Wracks aus dem Zweiten Weltkrieg, geheimnisvolle Grotten und Sichtweiten bis 40 Meter – Malta ist das Tauchmekka Europas.',
    climateKey: 'malta',
    tips: [
      'Blue Hole auf Gozo ist einer der bekanntesten Tauchplätze Europas – atemberaubende Unterwasserbogen.',
      'HMS Maori und Tug 2 sind Wrack-Tauchgänge direkt vor Valletta – für zertifizierte Taucher.',
      'Tauchen ganzjährig möglich – Wassertemperatur im Winter 14 °C, im Sommer 26 °C.',
      'Zahlreiche PADI-zertifizierte Tauchschulen auf Malta und Gozo für Anfängerkurse.',
      'Sichtweiten bis 40+ Meter im Sommer – einzigartig im Mittelmeer.',
    ],
    faqs: [
      { q: 'Warum ist Malta ein Top-Tauchziel?', a: 'Kristallklares Wasser (Sichtweite bis 40 m), keine Gezeiten, ganzjährig tauchbar, Wracks, Höhlen und reiches Meeresleben.' },
      { q: 'Was ist der Blue Hole auf Gozo?', a: 'Ein natürlicher Felsbogen unter Wasser auf Gozo – einer der fotogensten und bekanntesten Tauchplätze der Welt. Auch für Schnorchler zugänglich.' },
      { q: 'Kann man in Malta einen Tauchkurs machen?', a: 'Ja, zahlreiche PADI- und SSI-Schulen bieten Anfängerkurse (Open Water) ab ca. 300–400 € auf Malta und Gozo an.' },
      { q: 'Wie kalt ist das Wasser in Malta?', a: 'Im Sommer 25–26 °C. Im Winter 14–16 °C (Neoprenanzug empfohlen). Frühling und Herbst 18–22 °C.' },
      { q: 'Welche Meerestiere sieht man beim Tauchen in Malta?', a: 'Oktopusse, Barrakudas, Muränen, Meerbrassen, Goldmakrelen und seltene Loggerhead-Meeresschildkröten.' },
    ],
  },
  {
    id: 'wuestensafari-dubai',
    file: 'wuestensafari-dubai.html',
    type: 'aktivitaet',
    icon: '🐪',
    nameDe: 'Dubai',
    aktivitaet: 'Wüstensafari',
    title: 'Wüstensafari Dubai 2026 – Tipps, Preise & Anbieter | JetztBuchbar.de',
    description: 'Wüstensafari in Dubai 2026: Dünenfahrt, Kamelreiten, Beduinencamp. Alle Infos zu Ablauf, Preisen und besten Anbietern.',
    h1Parts: ['Wüstensafari in', 'Dubai'],
    heroSub: 'Eine Dune-Bashing-Tour bei Sonnenuntergang, Kamelreiten und ein Abendessen unter dem Sternenhimmel – die Wüstensafari ist das unverzichtbare Dubai-Erlebnis.',
    climateKey: 'dubai',
    tips: [
      'Abend-Safari (ab 15:00 Uhr) ist die beliebteste Option – Sonnenuntergang in der Wüste + Abendessen im Camp.',
      'Frühbuchen: Safaris über offizielle Veranstalter oder Hotel-Concierge buchen, nicht von Straßenhändlern.',
      'Leichte, luftige Kleidung – aber Schultern bedecken beim Beduinencamp-Besuch.',
      'Sandboarding und Quad-Bikes werden oft als Zusatz angeboten – im Voraus konfigurieren.',
      'Wer photografieren will: Kamera auf Dune-Bashing in geschlossener Tasche sichern.',
    ],
    faqs: [
      { q: 'Was ist bei einer Dubai-Wüstensafari inklusive?', a: 'Typischerweise: Transfer vom Hotel, Dune Bashing (Geländewagenfahrt), Kamelritt, Sandboarding, Falknerei, BBQ-Abendessen, Live-Unterhaltung (Bauchttanz, Tanoura).' },
      { q: 'Was kostet eine Wüstensafari in Dubai?', a: 'Standard-Abendsafari ca. 40–70 € pro Person. Luxury-Safaris mit privatem Camp ab 150–300 € pro Person.' },
      { q: 'Wann ist die beste Zeit für eine Wüstensafari in Dubai?', a: 'Oktober bis April – angenehme Temperaturen (25–35 °C). Sommer ist möglich, aber extrem heiß (45 °C+).' },
      { q: 'Ist die Wüstensafari für Kinder geeignet?', a: 'Ab ca. 3 Jahren ja, aber Dune Bashing kann bei kleinen Kindern und schwangeren Frauen unangenehm sein. Sanftere "Morning Safari" ist familienfreundlicher.' },
      { q: 'Wie weit ist die Wüste von Dubai entfernt?', a: 'Die Wüste beginnt ca. 45–60 km östlich vom Stadtzentrum. Transfer inklusive bei Tourbuchungen (ca. 45–60 Minuten).' },
    ],
  },
  {
    id: 'wandern-kroatien',
    file: 'wandern-kroatien.html',
    type: 'aktivitaet',
    icon: '🥾',
    nameDe: 'Kroatien',
    aktivitaet: 'Wandern',
    title: 'Wandern in Kroatien 2026 – Nationalparks & Küstenwege | JetztBuchbar.de',
    description: 'Wandern in Kroatien 2026: Plitvicer Seen, Nationalpark Krka, Velebit. Beste Routen, Schwierigkeiten und Tipps.',
    h1Parts: ['Wandern in', 'Kroatien'],
    heroSub: 'Von den türkisen Kaskaden der Plitvicer Seen bis zu den Kalksteinkämmen des Velebit-Gebirges – Kroatien bietet Wanderparadiese für jeden Level.',
    climateKey: 'kroatien',
    tips: [
      'Plitvicer Seen: Frühmorgens (7–8 Uhr) besuchen, um Menschenmassen zu vermeiden – UNESCO-Welterbe.',
      'Paklenica-Nationalpark: Klettersteige und Wanderwege für alle Schwierigkeitsgrade nahe der Küste.',
      'Frühjahr (April–Mai) und Herbst (September–Oktober) sind ideale Wanderzeit – weniger Hitze, weniger Touristen.',
      'Wasser und Sonnenschutz immer mitnehmen – Schatten ist auf den Karstfelsen begrenzt.',
      'Nationale Park-Eintritte vorher online kaufen – Plitvicer Seen oft ausgebucht.',
    ],
    faqs: [
      { q: 'Welcher Nationalpark eignet sich am besten für Wanderer?', a: 'Plitvicer Seen für Naturerlebnis, Paklenica für Bergwandern und Klettern, Velebit für mehrtägige Touren, Krka für leichte Familienwanderungen.' },
      { q: 'Wie schwierig ist das Wandern in den Plitvicer Seen?', a: 'Die meisten Wege sind flach und für alle geeignet. Strecken 2–8 km je nach Route. Befestigte Holzstege – auch für ältere Wanderer gut.' },
      { q: 'Brauche ich besondere Ausrüstung für Wanderungen in Kroatien?', a: 'Feste Wanderschuhe und Wasser reichen für die meisten Wege. Für Paklenica-Klettersteige ist Kletterausrüstung empfohlen.' },
      { q: 'Kann man am Velebit mehrtägig wandern?', a: 'Ja, der Premuzic-Weg (57 km) ist ein klassischer Weitwanderweg auf dem Velebit-Kamm mit Hütten. Für geübte Wanderer.' },
      { q: 'Wann ist die Wandersaison in Kroatien?', a: 'April bis Oktober ist ideal. Im Sommer (Juli–August) sehr heiß an der Küste – Bergwanderwege im Inland besser geeignet.' },
    ],
  },
  {
    id: 'surfen-kap-verde',
    file: 'surfen-kap-verde.html',
    type: 'aktivitaet',
    icon: '🏄',
    nameDe: 'Kap Verde',
    aktivitaet: 'Surfen',
    title: 'Surfen auf Kap Verde 2026 – Kitesurfen & Windsurfen | JetztBuchbar.de',
    description: 'Surfen auf Kap Verde 2026: Sal, Boa Vista, São Vicente. Bestes Windsurf- und Kitesurfziel der Welt. Tipps, Schulen, beste Saison.',
    h1Parts: ['Surfen auf', 'Kap Verde'],
    heroSub: 'Konstanter Passat, türkisblaues Wasser und 300 Sonnentage: Kap Verde gehört zu den weltweit besten Windsurf- und Kitesurfzielen.',
    climateKey: 'kap verde',
    tips: [
      'Santa Maria auf Sal ist das Weltzentrum für Kitesurfen – Weltcup-Wettbewerbe werden hier ausgetragen.',
      'Windstärke auf Sal: 4–6 Beaufort konstant (Juni–September stärker). Ideal für Anfänger und Profis.',
      'Surfschulen vor Ort bieten Kurse für alle Level – Kite-Anfängerkurs ab ca. 150–250 €.',
      'Wellensurfen auf São Vicente (Mindelo) für fortgeschrittene Surfer mit größeren Wellen.',
      'Ganzjährig surfbar – keine Saison, kein Monsun. Konstanteste Winde weltweit.',
    ],
    faqs: [
      { q: 'Warum ist Kap Verde ein Top-Surfziel?', a: 'Konstanter Nordostpassat (ganzjährig), warmes Wasser (24–28 °C), perfekte Wellen für alle Level und hervorragende Infrastruktur auf Sal.' },
      { q: 'Welche Insel für welchen Surfsport?', a: 'Sal für Kitesurfen und Windsurfen (flaches Wasser), São Vicente für Wellensurfen, Boa Vista ebenfalls für Kite mit weniger Trubel.' },
      { q: 'Kann man als Anfänger auf Kap Verde surfen lernen?', a: 'Ja, besonders Kite- und Windsurf-Anfänger kommen auf Kap Verde schnell voran – ideale Bedingungen und professionelle Schulen.' },
      { q: 'Was kostet ein Surf-Urlaub auf Kap Verde?', a: 'All-in-Surfpaket (Flug + Hotel + Kurs, 1 Woche) ab ca. 900–1.500 € pro Person. Ausrüstungsverleih vor Ort ab 40–70 €/Tag.' },
      { q: 'Wie warm ist das Wasser auf Kap Verde?', a: 'Konstant 24–28 °C ganzjährig – kein Neoprenanzug nötig, kurzer Surfsuit reicht völlig aus.' },
    ],
  },
];

// ── Region/Küste pages ────────────────────────────────────────────────────────

const REGION_PAGES = [
  {
    id: 'algarve',
    file: 'algarve.html',
    type: 'region',
    icon: '🪨',
    nameDe: 'Algarve',
    land: 'Portugal',
    title: 'Algarve Urlaub 2026 – Felsenküste, Strände & Tipps | JetztBuchbar.de',
    description: 'Algarve 2026: Portugals schönste Küste mit Felsen, goldenen Stränden und Golftourismus. Beste Orte, Reisezeit und Angebote.',
    h1Parts: ['Urlaub an der', 'Algarve'],
    heroSub: 'Goldene Kalksteinfelsen, türkisblaues Atlantikmeer und entspannte Dörfer – die Algarve ist Portugals schönstes Strandparadies.',
    climateKey: 'algarve',
    tips: [
      'Lagos, Albufeira und Tavira sind die bekanntesten Orte – Lagos für Backpacker, Tavira für Ruhesuchende.',
      'Beste Reisezeit: Mai bis Oktober. Juni und September ideal – weniger Massen als Juli/August.',
      'Mietwagen empfohlen: Die schönsten versteckten Buchten sind nur auf schmalen Küstenstraßen erreichbar.',
      'Ponta da Piedade bei Lagos ist ein absolutes Muss – Bootstour zu den Grotten buchen.',
      'Golf: Die Algarve hat über 40 Golfplätze – Weltniveau und günstigere Greenfees als in anderen Ländern.',
    ],
    faqs: [
      { q: 'Welcher Ort an der Algarve ist der beste?', a: 'Lagos für junge Reisende und Surfer, Albufeira für Partytourismus, Tavira für Ruhe und Authentizität, Vilamoura für Luxus und Golf.' },
      { q: 'Wann ist die beste Reisezeit für die Algarve?', a: 'Mai–Juni und September–Oktober: gutes Wetter (24–28 °C), weniger Touristen, günstigere Preise. Juli/August heiß und voll.' },
      { q: 'Wie kommt man an die Algarve?', a: 'Direktflug nach Faro (2,5–3 Stunden von Wien/München), dann Mietwagen. Oder Fliegen nach Lissabon und 3 Stunden Zug/Auto.' },
      { q: 'Was kostet Urlaub an der Algarve?', a: 'Günstiger als Westeuropa: Hotel ab 60–100 €/Nacht, Essen moderat. Mietwagen ab 25 €/Tag. Insgesamt erschwinglicher als Mallorca oder Côte d\'Azur.' },
      { q: 'Gibt es gute Surfspots an der Algarve?', a: 'Ja, besonders Sagres und Arrifana im Westen sind bekannte Surforte mit guten Atlantikwellen für alle Level.' },
    ],
  },
  {
    id: 'costa-brava',
    file: 'costa-brava.html',
    type: 'region',
    icon: '🌊',
    nameDe: 'Costa Brava',
    land: 'Spanien',
    title: 'Costa Brava Urlaub 2026 – Spaniens wilder Küste | JetztBuchbar.de',
    description: 'Costa Brava 2026: Felsige Buchten, Küstenwanderung und Dalí-Museen. Die schönste Region Kataloniens für Aktivurlauber.',
    h1Parts: ['Urlaub an der', 'Costa Brava'],
    heroSub: 'Zerklüftete Felsenküste, geheime Calas und Salvador Dalís Heimat – die Costa Brava ist Spaniens wildeste und romantischste Küste.',
    climateKey: 'barcelona',
    tips: [
      'Cadaqués und Begur sind authentische Fischerdörfer ohne Massentourismus – perfekt für Ruhe und Fotografie.',
      'Camí de Ronda – der 220 km lange Küstenwanderweg entlang der gesamten Costa Brava.',
      'Dalí-Dreieck: Museen in Figueres, Cadaqués und Púbol lohnen sich für alle Kulturinteressierten.',
      'Lloret de Mar und Tossa de Mar für klassischen Badetourismus, Cabo Creus für Natur.',
      'Mietwagen empfohlen – versteckte Buchten (Calas) sind ohne eigenes Auto schwer erreichbar.',
    ],
    faqs: [
      { q: 'Was bedeutet Costa Brava?', a: '"Wilde Küste" – benannt nach den zerklüfteten Felsen und wilden Buchten der nordspanischen Mittelmeerküste in Katalonien.' },
      { q: 'Wo ist die Costa Brava?', a: 'Im Norden Kataloniens, von Blanes bis zur französischen Grenze. Nächste Flughäfen: Girona (klein, günstig) und Barcelona-El Prat (größer, mehr Verbindungen).' },
      { q: 'Was sind die schönsten Orte an der Costa Brava?', a: 'Cadaqués (das schönste Dorf), Begur (für Strände), Tossa de Mar (mittelalterliche Burg), Pals (historisches Dörfchen).' },
      { q: 'Wann ist die beste Zeit für die Costa Brava?', a: 'Mai–Juni und September–Oktober. Juli/August sehr heiß und voll. Wassertemperatur im September noch 24 °C.' },
      { q: 'Kann man an der Costa Brava tauchen?', a: 'Ja, das Meeresschutzgebiet Cabo Creus gilt als eines der besten Tauchabschnitte im Mittelmeer mit reicher Unterwasserwelt.' },
    ],
  },
  {
    id: 'bodensee-region',
    file: 'bodensee-region.html',
    type: 'region',
    icon: '⛵',
    nameDe: 'Bodensee',
    land: 'Deutschland/Österreich/Schweiz',
    title: 'Bodensee Urlaub 2026 – Entspannung am größten Alpensee | JetztBuchbar.de',
    description: 'Bodensee 2026: Konstanz, Bregenz, Lindau. Radfahren, Segeln und Ausflüge auf drei Länder. Tipps für die ganze Familie.',
    h1Parts: ['Urlaub am', 'Bodensee'],
    heroSub: 'Drei Länder, ein See: Am Bodensee verbindet sich bayerisches Flair, österreichische Gemütlichkeit und Schweizer Präzision zu einem unvergesslichen Urlaubsgebiet.',
    climateKey: 'münchen',
    tips: [
      'Fahrrad ist das beste Verkehrsmittel – der 273 km lange Bodensee-Radweg führt komplett um den See.',
      'Insel Mainau (Blumeninsel) und Insel Reichenau (UNESCO-Welterbe) sind Tagesausflugsziele von höchster Güte.',
      'Bregenz Festspiele im Sommer – weltberühmte Seebühnen-Oper, Tickets früh buchen.',
      'Konstanz Altstadt für Shopping und Gastronomie – günstige Schweizer Franken auf der gegenüberliegenden Seeseite.',
      'Obst- und Weinregion: Bodenseeäpfel und Weißweine direkt beim Winzer probieren.',
    ],
    faqs: [
      { q: 'Wo liegt der Bodensee?', a: 'Dreiländereck: Deutschland (Bayern und Baden-Württemberg), Österreich (Vorarlberg) und Schweiz (Kanton Thurgau und St. Gallen).' },
      { q: 'Was kann man am Bodensee unternehmen?', a: 'Radfahren, Segeln, Schwimmen, Wandern, Museen, Bodenseeschifffahrt, Zeppelin-Museum Friedrichshafen, Pfahlbauten Unteruhldingen.' },
      { q: 'Wann ist die beste Reisezeit für den Bodensee?', a: 'Mai bis September. Wassertemperatur im Sommer ca. 22–24 °C. Herbst für Weinlese und Ruhe, wenige Touristen.' },
      { q: 'Wie teuer ist Urlaub am Bodensee?', a: 'Deutschland-typisches Preisniveau. Hotels ab 70–120 €/Nacht. Schweizer Seite etwas teurer. Insgesamt familienfreundliche Preise.' },
      { q: 'Gibt es direkten Bahnzugang zum Bodensee?', a: 'Ja, ICE/EC-Züge direkt nach Konstanz und Lindau von Wien (ca. 3,5 Std.) und München (ca. 1,5 Std.). Sehr gut mit Bahn erreichbar.' },
    ],
  },
  {
    id: 'amalfikueste',
    file: 'amalfikueste.html',
    type: 'region',
    icon: '🍋',
    nameDe: 'Amalfiküste',
    land: 'Italien',
    title: 'Amalfiküste Urlaub 2026 – Positano, Ravello & Tipps | JetztBuchbar.de',
    description: 'Amalfiküste 2026: Positano, Amalfi, Ravello. Eine der schönsten Küsten der Welt – Tipps, beste Zeit und Angebote.',
    h1Parts: ['Urlaub an der', 'Amalfiküste'],
    heroSub: 'Pastellfarbene Häuser auf Klippen, Zitronenwälder und tiefblaues Tyrrhenisches Meer – die Amalfiküste ist das romantischste Reiseziel Italiens.',
    climateKey: 'neapel',
    tips: [
      'Positano, Amalfi und Ravello sind die Highlights – Ravello für Ruhe und Ausblick, Positano für Fotos.',
      'Autovermietung ist nicht empfohlen – Straßen extrem eng. Fähren und Busse sind die beste Option.',
      'Frühsaison (April–Mai) und Nachsaison (September–Oktober) für ruhigere Atmosphäre und faire Preise.',
      'Von Neapel oder Sorrent aus leicht erreichbar – Tagesausflug oder Mehrtagesaufenthalt möglich.',
      'Limoncello-Produzenten besuchen – authentische Zitronenlikör-Herstellung direkt in den Hügeln.',
    ],
    faqs: [
      { q: 'Wie kommt man zur Amalfiküste?', a: 'Flug nach Neapel, dann Zug nach Sorrent (50 Min.) und Fähre oder Bus zur Amalfiküste. Oder direkte Fähre von Neapel nach Amalfi/Positano (Sommer).' },
      { q: 'Was kostet Urlaub an der Amalfiküste?', a: 'Die Amalfiküste ist teuer: Hotels ab 150–300 €/Nacht. Essen im Restaurant ab 30–50 € pro Person. Einer der teureren Teile Italiens.' },
      { q: 'Was sind die schönsten Orte an der Amalfiküste?', a: 'Positano (photogenste Stadt), Ravello (Musik und Aussicht), Atrani (kleinste Stadt Italiens), Vietri sul Mare (Keramik).' },
      { q: 'Wann ist die beste Zeit für die Amalfiküste?', a: 'Mai und September – ideales Wetter (25–28 °C), weniger Touristen als Juli/August, angenehme Preise.' },
      { q: 'Gibt es Strände an der Amalfiküste?', a: 'Ja, aber eher kleine Kieselstrände. Praiano und Marina d\'Amalfi für Schwimmen. Keine langen Sandstrände wie in anderen Regionen Italiens.' },
    ],
  },
];

// ── Reisetipps pages ──────────────────────────────────────────────────────────

const REISETIPPS_PAGES = [
  {
    id: 'handgepaeck-regeln',
    file: 'handgepaeck-regeln.html',
    type: 'reisetipps',
    icon: '🧳',
    thema: 'Handgepäck',
    title: 'Handgepäck Regeln 2026 – Was ist erlaubt? | JetztBuchbar.de',
    description: 'Handgepäck-Regeln 2026 für alle Fluggesellschaften: Maße, Gewicht, Flüssigkeiten. Alles was Sie wissen müssen vor dem Abflug.',
    h1Parts: ['Handgepäck', 'Regeln 2026'],
    heroSub: 'Maße, Gewichte, Flüssigkeiten, Laptops – alles was Sie über Handgepäck wissen müssen, damit der Check-in reibungslos klappt.',
    tips: [
      'Standardmaß für Handgepäck: 55 × 40 × 20 cm (IATA-Empfehlung) – aber Airlines weichen ab!',
      'Flüssigkeiten: max. 100 ml pro Behälter, alle in einem 1-Liter-Zip-Beutel, offen vorzeigen.',
      'Laptops und Tablets müssen separat aus dem Rucksack genommen werden am Sicherheitscheck.',
      'Powerbanks nur im Handgepäck erlaubt (nie im Koffer) – max. 100 Wh ohne Genehmigung.',
      'Budget-Airlines (Ryanair, Wizz Air) verlangen oft Aufpreis für Bordgepäck – bei Buchung prüfen.',
    ],
    faqs: [
      { q: 'Welche Handgepäck-Größe erlaubt die Lufthansa?', a: '55 × 40 × 23 cm, max. 8 kg. Plus kleines Zusatzgepäckstück (Handtasche, Laptop-Rucksack) bis 40 × 30 × 10 cm.' },
      { q: 'Was gilt als Flüssigkeit im Handgepäck?', a: 'Alles Flüssige, Pastöse und Cremes: Wasser, Parfüm, Zahnpasta, Gel, Shampoo, Mascara. Max. 100 ml pro Behälter, alles in 1-L-Beutel.' },
      { q: 'Kann ich Medikamente im Handgepäck mitnehmen?', a: 'Ja, mit Arztzeugnis oder Rezept auch über 100 ml. Am Sicherheitscheck separat vorzeigen und dokumentieren lassen.' },
      { q: 'Darf ich Powerbank im Handgepäck mitnehmen?', a: 'Ja, Powerbanks bis 100 Wh (ca. 27.000 mAh) ohne Genehmigung. Im Koffer verboten – Brandgefahr.' },
      { q: 'Was passiert, wenn mein Handgepäck zu groß ist?', a: 'Die Airline kann es als Aufgabegepäck einchecken lassen – oft gegen Gebühr (20–80 €). Im schlimmsten Fall wird das Gepäck abgenommen.' },
    ],
  },
  {
    id: 'reiseversicherung-vergleich',
    file: 'reiseversicherung-vergleich.html',
    type: 'reisetipps',
    icon: '🛡️',
    thema: 'Reiseversicherung',
    title: 'Reiseversicherung 2026 – Vergleich & Tipps | JetztBuchbar.de',
    description: 'Reiseversicherung 2026 vergleichen: Reiserücktritt, Auslandskranken und Reiseabbruch. Welche Versicherung brauche ich wirklich?',
    h1Parts: ['Reiseversicherung', 'Vergleich 2026'],
    heroSub: 'Welche Reiseversicherung brauche ich wirklich? Wir erklären die Unterschiede und zeigen, wann sich welcher Schutz lohnt.',
    tips: [
      'Auslandskrankenversicherung ist Pflicht für alle Nicht-EU-Reiseziele – die EHIC gilt nur in der EU.',
      'Reiserücktrittsversicherung lohnt sich bei Buchungen über 500 € – deckt Stornierungskosten bei Krankheit.',
      'Jahres-Reiseversicherung rechnet sich ab zwei Reisen pro Jahr gegenüber Einzelabschlüssen.',
      'Kreditkarten-Versicherungen genau prüfen – oft nur Teilschutz, Deckungssummen begrenzt.',
      'Pandemie-Klauseln seit COVID wichtig – manche Policen schließen pandemiebedingte Stornierungen aus.',
    ],
    faqs: [
      { q: 'Welche Reiseversicherung brauche ich für die Türkei?', a: 'Auslandskrankenversicherung ist Pflicht – die EU-Krankenversicherungskarte (EHIC) gilt nicht in der Türkei. Reiserücktritt empfohlen bei teureren Buchungen.' },
      { q: 'Ist eine Reiseversicherung über die Kreditkarte ausreichend?', a: 'Oft nicht vollständig. Kreditkarten-Versicherungen haben oft begrenzte Deckungssummen, Ausschlüsse und erfordern, dass die Reise mit der Karte bezahlt wurde.' },
      { q: 'Was kostet eine Jahres-Reisekrankenversicherung?', a: 'Für Einzelpersonen ca. 15–40 €/Jahr, Familien ca. 30–80 €/Jahr. Rechnet sich sehr schnell bei mehreren Reisen.' },
      { q: 'Was deckt eine Reiserücktrittsversicherung ab?', a: 'Stornierungskosten bei unerwarteter Krankheit, Unfall oder Tod – eigene oder naher Angehöriger. Deckt nicht: "Lust verloren", Streik, Wetter.' },
      { q: 'Gibt es eine Versicherung, die alles abdeckt?', a: 'Kombi-Pakete (All-Risk) decken Rücktritt + Auslandskranken + Abbruch + Gepäck in einem ab. Oft das beste Preis-Leistungs-Verhältnis für längere Reisen.' },
    ],
  },
  {
    id: 'packliste-sommerurlaub',
    file: 'packliste-sommerurlaub.html',
    type: 'reisetipps',
    icon: '☀️',
    thema: 'Packliste',
    title: 'Packliste Sommerurlaub 2026 – Was muss mit? | JetztBuchbar.de',
    description: 'Die ultimative Packliste für den Sommerurlaub 2026: Strand, Kultur und Allwetter. Alles was Sie einpacken müssen – nichts vergessen.',
    h1Parts: ['Packliste', 'Sommerurlaub'],
    heroSub: 'Damit der Koffer sitzt und nichts fehlt: Die komplette Packliste für den Sommerurlaub – von Sonnencreme bis Adapter.',
    tips: [
      'Rollen statt Falten: Kleidung gerollt spart bis zu 30 % Platz im Koffer.',
      'Sonnencreme am Urlaubsort kaufen ist oft günstiger als am Flughafen – aber Qualität prüfen.',
      'Universaladapter mitnehmen: In Dubai, der Türkei und Marokko gelten andere Stecker.',
      'Erste-Hilfe-Reiseapotheke: Pflaster, Ibuprofen, Durchfallmittel, Antihistaminika und Sonnenbrand-Spray.',
      'Digitale Kopien aller wichtigen Dokumente (Pass, Versicherung, Buchung) in der Cloud speichern.',
    ],
    faqs: [
      { q: 'Was darf im Koffer für den Strandurlaub auf keinen Fall fehlen?', a: 'Sonnencreme SPF 30/50, Flip-Flops, Schwimmbrille, Reiseapotheke, Ladekabel, Adapter, Wasserabweisende Strandtasche, Kopfbedeckung.' },
      { q: 'Wie viele Kleidungsstücke brauche ich für 1 Woche?', a: '5–7 T-Shirts, 3–4 Shorts/Röcke, 1 Abendoutfit, 7 Unterwäsche, 2–3 Badeanzüge/Badehosen. Waschen vor Ort möglich.' },
      { q: 'Welcher Adapter braucht man in der Türkei?', a: 'Türkei verwendet Typ C/F (Eurostecker) – der Standard in Deutschland, Österreich und der Schweiz. Kein Adapter nötig.' },
      { q: 'Muss ich Bargeld mitnehmen?', a: 'Ja, eine Notfallreserve in Euros (100–200 €) empfohlen. Am Urlaubsort dann Landeswährung am Geldautomaten (günstiger Kurs) abheben.' },
      { q: 'Darf ich Sonnencreme im Handgepäck mitnehmen?', a: 'Ja, aber nur in Behältern bis 100 ml im Zip-Beutel. Größere Flaschen müssen in den Koffer – oder am Ziel kaufen.' },
    ],
  },
  {
    id: 'guenstig-fliegen-tipps',
    file: 'guenstig-fliegen-tipps.html',
    type: 'reisetipps',
    icon: '✈️',
    thema: 'Günstig fliegen',
    title: 'Günstig fliegen 2026 – 10 Tipps für billige Flüge | JetztBuchbar.de',
    description: 'Günstige Flüge 2026 finden: Die besten Tipps für Last-Minute, Frühbuchung, flexible Reisedaten und Preisalarme.',
    h1Parts: ['Günstig fliegen', 'Tipps 2026'],
    heroSub: 'Mit den richtigen Strategien zahlen Sie deutlich weniger: Preisalarm, flexible Daten, versteckte City-Pairs und mehr – die besten Spartipps für Flüge.',
    tips: [
      'Dienstag und Mittwoch sind statistisch die günstigsten Abflugtage – Wochenenden teurer.',
      'Preisalarm-Tools nutzen: Google Flights, Skyscanner und Kayak informieren, wenn Preise fallen.',
      'Flexible Datum-Suche: 3 Tage früher oder später kann Hunderte Euro sparen.',
      'Nebensaison buchen: Mai, Juni und September sind meist 20–40 % günstiger als Juli/August.',
      'Frühbucher (4–6 Monate vorher) oder Last-Minute (7–14 Tage vorher) für beste Preise.',
    ],
    faqs: [
      { q: 'Wann bucht man Flüge am günstigsten?', a: 'Laut Studien: 4–8 Wochen vor Abflug für Europa-Intraflüge, 2–6 Monate vorher für Langstrecken. Last-Minute kann günstig sein, aber riskant.' },
      { q: 'Sind Frühbucherrabatte wirklich günstiger?', a: 'Oft ja, besonders bei beliebten Zielen wie Mallorca, Antalya oder Kreta im Sommer. Je früher, desto besser die Auswahl – aber Preisverfall ist auch möglich.' },
      { q: 'Lohnen sich Flüge mit Zwischenstopp?', a: 'Für Kurzstrecken selten. Für Langstrecken (z.B. Dubai, Kap Verde) kann ein Stopp in Istanbul oder Lissabon erheblich günstiger sein.' },
      { q: 'Was ist ein Hidden-City-Ticket?', a: 'Man bucht einen Flug mit Zwischenstopp und steigt am Zwischenstopp aus. Verboten von Airlines, führt bei Entdeckung zu Ärger. Nicht empfohlen.' },
      { q: 'Welche Apps helfen bei der Flugsuche?', a: 'Google Flights für Preiskalender, Skyscanner für Vergleiche, Kayak für Preistrends, Hopper für Kaufempfehlungen (steigt oder fällt der Preis?).' },
    ],
  },
];

// ── Vergleich pages ───────────────────────────────────────────────────────────

const VERGLEICH_PAGES = [
  {
    id: 'tuerkei-vs-aegypten',
    file: 'tuerkei-vs-aegypten.html',
    type: 'vergleich',
    icon: '⚖️',
    dest1: 'Türkei',
    dest2: 'Ägypten',
    title: 'Türkei oder Ägypten 2026? – Vergleich für Urlauber | JetztBuchbar.de',
    description: 'Türkei vs. Ägypten 2026: Preise, Wetter, Strände und Kultur im direkten Vergleich. Welches Ziel passt besser zu Ihnen?',
    h1Parts: ['Türkei oder', 'Ägypten?'],
    heroSub: 'Beide bieten Sonne, Strand und All-Inclusive – aber wo fährt man besser? Ein ehrlicher Vergleich für DACH-Urlauber.',
    tips: [
      'Türkei: bessere Infrastruktur, modernere Resorts, näher (3–3,5 Std. Flug vs. 4–4,5 Std. nach Ägypten).',
      'Ägypten: günstiger als Türkei, einzigartige Kulturerlebnisse (Pyramiden, Luxor), Rotes Meer für Taucher.',
      'Beide Länder erfordern eine Auslandskrankenversicherung – EU-Karte gilt nicht.',
      'Türkei: keine Impfungen nötig. Ägypten: Hepatitis A-Impfung empfohlen, Magenschutz.',
      'Beste Reisezeit: Türkei Mai–Oktober, Ägypten Oktober–April (Sommer zu heiß in Luxor).',
    ],
    faqs: [
      { q: 'Was ist günstiger – Türkei oder Ägypten?', a: 'Ägypten ist in der Regel etwas günstiger, besonders am Roten Meer (Hurghada). Türkei (Antalya) bietet aber besseres Preis-Leistungs-Verhältnis bei Resortqualität.' },
      { q: 'Wo sind die besseren Strände?', a: 'Türkei (Lara Beach, Ölüdeniz) und Ägypten (Hurghada Korallen, Sifah) bieten unterschiedliche Erlebnisse. Ägypten für Schnorchler/Taucher, Türkei für klassischen Strand.' },
      { q: 'Welches Land ist sicherer?', a: 'Beide gelten als touristisch sicher in den Ferienregionen. Aktuelle Reisehinweise des Außenministeriums vor der Reise prüfen.' },
      { q: 'Wo ist das Essen besser?', a: 'Türkische Küche ist vielfältiger und wird von den meisten Urlaubern besser bewertet. Ägyptisches Essen in Resorts oft internationale Küche.' },
      { q: 'Was ist besser für Familien mit Kindern?', a: 'Türkei gilt als familienfreundlicher – modernere Kinderclubs, mehr Animation, bessere medizinische Versorgung in Touristenzentren.' },
    ],
  },
  {
    id: 'mallorca-vs-kreta',
    file: 'mallorca-vs-kreta.html',
    type: 'vergleich',
    icon: '⚖️',
    dest1: 'Mallorca',
    dest2: 'Kreta',
    title: 'Mallorca oder Kreta 2026? – Vergleich für Urlauber | JetztBuchbar.de',
    description: 'Mallorca vs. Kreta 2026: Welche Insel ist besser für Ihren Urlaub? Preise, Strände, Kulinarik und Aktivitäten im Vergleich.',
    h1Parts: ['Mallorca oder', 'Kreta?'],
    heroSub: 'Zwei der beliebtesten Ferieninseln Europas – aber wo fährt man besser? Der direkte Vergleich für DACH-Urlauber.',
    climateKey: 'mallorca',
    tips: [
      'Mallorca: kürzer erreichbar (2–2,5 Std. vs. 3–3,5 Std. nach Kreta), weniger Hitze im Hochsommer.',
      'Kreta: deutlich größer, mehr Abwechslung zwischen Regionen, griechisches Flair.',
      'Mallorca: mehr Partytourismus (Ballermann), mehr Golftourismus, mehr Yachtkultur.',
      'Kreta: authentischere Gastronomie, mehr Wandermöglichkeiten, Schlucht von Samariá.',
      'Preise ähnlich – Kreta leicht günstiger für Essen und lokale Unterkünfte.',
    ],
    faqs: [
      { q: 'Was ist günstiger – Mallorca oder Kreta?', a: 'Kreta ist tendenziell etwas günstiger für Essen, Getränke und lokale Unterkünfte. Hotels auf beiden Inseln vergleichbar.' },
      { q: 'Wo sind die schöneren Strände?', a: 'Geschmackssache: Mallorca (Cala Mesquida, Playa de Muro) vs. Kreta (Elafonisi, Balos). Beide außergewöhnlich schön.' },
      { q: 'Welche Insel ist besser für Familien?', a: 'Beide sehr familienfreundlich. Alcúdia/Mallorca für ruhige Familienstrände, Rethymno/Kreta für Mischung aus Strand und Kultur.' },
      { q: 'Wo gibt es mehr Kultur?', a: 'Kreta hat mehr Kultur und Geschichte: Minoische Paläste (Knossos), venezianische Altstadt Chania. Mallorca hat Palma und Tramuntana-Gebirge.' },
      { q: 'Ist Kreta oder Mallorca besser für Wanderer?', a: 'Kreta – die Samariá-Schlucht (16 km) ist eine der spektakulärsten Wanderungen Europas. Mallorca hat die Serra de Tramuntana (UNESCO).' },
    ],
  },
  {
    id: 'dubai-vs-abu-dhabi',
    file: 'dubai-vs-abu-dhabi.html',
    type: 'vergleich',
    icon: '⚖️',
    dest1: 'Dubai',
    dest2: 'Abu Dhabi',
    title: 'Dubai oder Abu Dhabi 2026? – Welches ist besser? | JetztBuchbar.de',
    description: 'Dubai vs. Abu Dhabi 2026: Sehenswürdigkeiten, Preise, Strände und Atmosphäre im Vergleich. Wo lohnt sich der Urlaub mehr?',
    h1Parts: ['Dubai oder', 'Abu Dhabi?'],
    heroSub: 'Die beiden größten Emirate – aber welches ist die bessere Reisewahl? Ein ehrlicher Vergleich zu Sehenswürdigkeiten, Strände und Preisen.',
    climateKey: 'dubai',
    tips: [
      'Dubai: pulsierender, mehr Nightlife, bessere Shoppingmalls, Burj Khalifa – touristisch vollentwickelt.',
      'Abu Dhabi: ruhiger, kulturreicher, Sheikh-Zayed-Moschee (kostenloser Eintritt!), Louvre Abu Dhabi.',
      'Abu Dhabi ist ca. 1,5 Stunden von Dubai entfernt – Tagesausflug problemlos möglich.',
      'Preise in Abu Dhabi leicht günstiger als Dubai, besonders Hotels.',
      'Formula-1-Fans: Abu Dhabi ist Heimat des Yas Marina Circuit – Grand Prix im November.',
    ],
    faqs: [
      { q: 'Was ist der Hauptunterschied zwischen Dubai und Abu Dhabi?', a: 'Dubai ist kommerzieller und touristischer mit Superlativen (höchste Gebäude, größte Malls). Abu Dhabi ist die Hauptstadt der VAE, kulturreicher und ruhiger.' },
      { q: 'Welche Stadt ist besser für einen Kurztrip?', a: 'Dubai für 3–5 Tage ideal: mehr Sehenswürdigkeiten auf engem Raum. Abu Dhabi als Tagesausflug von Dubai oder für Kulturinteressierte.' },
      { q: 'Was kostet Hotel in Abu Dhabi vs. Dubai?', a: 'Abu Dhabi 10–20 % günstiger als Dubai. 4-Sterne in Abu Dhabi ab 70–100 €/Nacht vs. Dubai ab 90–120 €/Nacht.' },
      { q: 'Muss ich ein Visum für Abu Dhabi separat beantragen?', a: 'Nein. Wer ein VAE-Visum (Dubai) hat, kann sich frei in allen Emiraten bewegen – kein separates Visum für Abu Dhabi.' },
      { q: 'Gibt es Strände in beiden Städten?', a: 'Ja. Dubai: Jumeirah Beach, JBR. Abu Dhabi: Corniche Beach, Yas Island Beach. Abu Dhabi-Strände oft ruhiger und sauberer.' },
    ],
  },
];

// ── All pages combined ────────────────────────────────────────────────────────

const ALL_PAGES = [
  ...DESTINATION_PAGES,
  ...CITY_PAGES,
  ...REISEZEIT_PAGES,
  ...THEMA_PAGES,
  ...HOTEL_PAGES,
  ...AKTIVITAET_PAGES,
  ...REGION_PAGES,
  ...REISETIPPS_PAGES,
  ...VERGLEICH_PAGES,
];

module.exports = {
  DESTINATION_PAGES,
  CITY_PAGES,
  REISEZEIT_PAGES,
  THEMA_PAGES,
  HOTEL_PAGES,
  AKTIVITAET_PAGES,
  REGION_PAGES,
  REISETIPPS_PAGES,
  VERGLEICH_PAGES,
  ALL_PAGES,
};
